"use strict";

function startGuess(){
  const stats=currentPlayer.gameStats.guess||={plays:0,wins:0,losses:0,draws:0,best:null};
  const rounds=[{max:50,guesses:7,label:"CALIBRATION"},{max:100,guesses:7,label:"WIDE BAND"},{max:250,guesses:8,label:"DEEP SEARCH"},{max:500,guesses:9,label:"MASTER LOCK"},{max:500,guesses:9,label:"MOVING TARGET",moving:true}];
  const timers=new Set();let round=1,secret=0,attempts=0,totalGuesses=0,totalScore=0,clueTokens=2,cluesUsedRound=0,totalClues=0,currentGuess=null,usedClues=new Set(),ended=false;
  const randomSecret=max=>Math.floor(Math.random()*max)+1;
  const schedule=(fn,delay)=>{const id=setTimeout(()=>{timers.delete(id);fn()},delay);timers.add(id)};
  const stop=()=>{window.removeEventListener("keydown",enterHandler);timers.forEach(clearTimeout);timers.clear()};
  const finish=won=>{if(ended)return;ended=true;stop();stats.highestCompletedRound=Math.max(stats.highestCompletedRound||0,won?5:round-1);stats.bestTotalScore=Math.max(stats.bestTotalScore||0,totalScore);if(won){stats.fewestTotalGuesses=Math.min(Number.isFinite(stats.fewestTotalGuesses)?stats.fewestTotalGuesses:Infinity,totalGuesses);if(totalClues===0)stats.perfectRuns=(stats.perfectRuns||0)+1}setStage(`<div class="guess-report"><p class="eyebrow">DEDUCTION CAMPAIGN</p><h3>${won?"ALL FIVE LOCKS OPEN":"CAMPAIGN INTERRUPTED"}</h3><div class="career-grid"><article><span>ROUND</span><b>${won?5:round-1}/5</b></article><article><span>TOTAL SCORE</span><b>${totalScore}</b></article><article><span>TOTAL GUESSES</span><b>${totalGuesses}</b></article><article><span>CLUES LEFT</span><b>${clueTokens}</b></article></div><p>BEST ${stats.bestTotalScore} • FEWEST ${Number.isFinite(stats.fewestTotalGuesses)?stats.fewestTotalGuesses:"—"} • NO-CLUE RUNS ${stats.perfectRuns||0}</p><button id="guess-again" class="pixel-btn primary">NEW CAMPAIGN</button></div>`);reward(Math.max(0,Math.round(totalScore/140)),Math.max(5,Math.round(totalScore/100)),{result:won?"win":"loss",score:totalScore});$("#guess-again").onclick=startGuess};
  const updateHud=()=>{$("#guess-attempts").textContent=`${attempts}/${rounds[round-1].guesses}`;$("#guess-score").textContent=totalScore;$("#guess-tokens").textContent=clueTokens;$$('[data-guess-clue]').forEach(button=>button.disabled=clueTokens<=0||usedClues.has(button.dataset.guessClue)||(button.dataset.guessClue==="near"&&currentGuess==null))};
  const useClue=type=>{if(ended||clueTokens<=0||usedClues.has(type))return;if(type==="near"&&currentGuess==null)return toast("MAKE A GUESS FIRST");clueTokens--;cluesUsedRound++;totalClues++;usedClues.add(type);const message=type==="parity"?`SIGNAL: THE TARGET IS ${secret%2?"ODD":"EVEN"}`:type==="three"?`SIGNAL: ${secret%3===0?"DIVISIBLE":"NOT DIVISIBLE"} BY 3`:`SIGNAL: TARGET IS ${Math.abs(secret-currentGuess)<=10?"WITHIN":"NOT WITHIN"} ±10 OF ${currentGuess}`;const log=$("#guess-clue-log");log.innerHTML+=`<span>${message}</span>`;updateHud()};
  const submit=()=>{if(ended)return;const config=rounds[round-1],input=$("#guess-input"),value=Number(input.value);if(!Number.isInteger(value)||value<1||value>config.max)return toast(`ENTER 1–${config.max}`);attempts++;totalGuesses++;currentGuess=value;if(value===secret){const roundScore=Math.max(100,1000-attempts*90-cluesUsedRound*150+round*100);totalScore+=roundScore;stats.highestCompletedRound=Math.max(stats.highestCompletedRound||0,round);saveData();$("#guess-result").textContent=`LOCK OPEN • +${roundScore} POINTS`;updateHud();if(round===5)return schedule(()=>finish(true),750);round++;return schedule(beginRound,750)}if(attempts>=config.guesses){$("#guess-result").textContent=`LOCK FAILED • TARGET WAS ${secret}`;updateHud();return schedule(()=>finish(false),950)}const direction=value<secret?"HIGHER ↑":"LOWER ↓";let movement="";if(config.moving){const before=secret,delta=Math.floor(Math.random()*7)-3;secret=Math.max(1,Math.min(config.max,secret+delta));movement=` • TARGET SHIFT ${secret-before>=0?"+":""}${secret-before}`}$("#guess-result").textContent=`${direction} • ${config.guesses-attempts} GUESSES LEFT${movement}`;input.value="";input.focus();updateHud()};
  const beginRound=()=>{const config=rounds[round-1];secret=randomSecret(config.max);attempts=0;cluesUsedRound=0;currentGuess=null;usedClues=new Set();setStage(`<div class="guess-campaign"><div class="game-score">ROUND ${round}/5 • ${config.label} • SCORE <b id="guess-score">${totalScore}</b></div><div class="guess-range"><small>ACTIVE RANGE</small><b>1 — ${config.max}</b>${config.moving?"<em>↔ TARGET MOVES AFTER EVERY WRONG GUESS</em>":""}</div><div class="guess-status"><span>GUESSES <b id="guess-attempts">0/${config.guesses}</b></span><span>CLUE TOKENS <b id="guess-tokens">${clueTokens}</b></span></div><div class="guess-controls"><input id="guess-input" class="game-input" type="number" min="1" max="${config.max}" placeholder="ENTER YOUR DEDUCTION"><button id="guess-btn" class="pixel-btn primary">SUBMIT GUESS</button></div><div class="guess-clues"><button data-guess-clue="parity">EVEN / ODD</button><button data-guess-clue="three">DIVISIBLE BY 3</button><button data-guess-clue="near" disabled>WITHIN ±10</button></div><div id="guess-clue-log" class="guess-clue-log"></div><p id="guess-result" class="result">Open the lock with as few guesses and clues as possible.</p></div>`);$("#guess-btn").onclick=submit;$$('[data-guess-clue]').forEach(button=>button.onclick=()=>useClue(button.dataset.guessClue));$("#guess-input").focus();updateHud()};
  const enterHandler=e=>{if(e.key==="Enter"&&document.activeElement?.id==="guess-input")submit()};window.addEventListener("keydown",enterHandler);setActiveCleanup(stop);beginRound();
}

GubuntuGames.register("guess",startGuess);
