"use strict";

function startMemory(launchOptions=null){
  const preselectedDifficulty=typeof launchOptions==="string"?launchOptions:launchOptions?.difficulty;
  const stats=currentPlayer.gameStats.memory||={plays:0,wins:0,losses:0,draws:0,best:null};
  if(["easy","normal","hard"].includes(preselectedDifficulty))return beginMemory(preselectedDifficulty);
  setStage(`<div class="arcade-mode-select"><p class="eyebrow">MEMORY RUN PROTOCOL</p><h3>SELECT DIFFICULTY</h3><div class="arcade-mode-grid"><button data-memory-difficulty="easy"><b>EASY</b><small>Starts 4×4 • Unlimited time</small></button><button data-memory-difficulty="normal"><b>NORMAL</b><small>Starts 5×4 • 90 seconds</small></button><button data-memory-difficulty="hard"><b>HARD</b><small>Starts 6×4 • 75 seconds</small></button></div><div class="quiz-career-strip"><span>BEST SCORE <b>${stats.bestScore||0}</b></span><span>FEWEST MOVES <b>${Number.isFinite(stats.fewestMoves)?stats.fewestMoves:"—"}</b></span><span>FASTEST <b>${Number.isFinite(stats.fastestCompletion)?`${stats.fastestCompletion}s`:"—"}</b></span><span>HIGHEST LEVEL <b>${stats.highestLevel||0}/3</b></span></div></div>`);
  $$('[data-memory-difficulty]').forEach(button=>button.onclick=()=>beginMemory(button.dataset.memoryDifficulty));
  function beginMemory(difficulty){
    const configs={easy:[{cols:4,rows:4,time:0},{cols:5,rows:4,time:0},{cols:6,rows:4,time:0}],normal:[{cols:5,rows:4,time:90},{cols:6,rows:4,time:82},{cols:6,rows:5,time:75}],hard:[{cols:6,rows:4,time:75},{cols:6,rows:5,time:65},{cols:6,rows:6,time:55}]}[difficulty],icons=["👾","🚀","⭐","💎","🛸","🤖","🍒","⚡","🌙","🦊","🐲","🎮","🧠","👻","🔥","🌊","🪐","🏆"],started=Date.now();
    let level=1,totalScore=0,totalMoves=0,combo=0,cards=[],open=[],done=new Set(),locked=false,remaining=0,timer=null,transitionTimer=null,peekTimer=null,ended=false;
    const multiplier=()=>combo>=6?2:combo>=4?1.5:combo>=2?1.25:1;
    const stopTimers=()=>{clearInterval(timer);clearTimeout(transitionTimer);clearTimeout(peekTimer)};
    const cardNodes=()=>$$('.memory-card');
    const buildDeck=(pairs,stage)=>{const specials=stage===1?[{key:"time",icon:"⏱",type:"time"}]:stage===2?[{key:"reveal",icon:"◉",type:"reveal"}]:[{key:"time",icon:"⏱",type:"time"},{key:"reveal",icon:"◉",type:"reveal"},{key:"trap",icon:"⚠",type:"trap"}],normalCount=Math.max(0,pairs-specials.length),defs=[...icons.slice(0,normalCount).map((icon,index)=>({key:`normal-${index}`,icon,type:"normal"})),...specials];return shuffle(defs.flatMap(def=>[{...def},{...def}]))};
    const updateHud=()=>{$("#memory-score").textContent=totalScore;$("#memory-moves").textContent=totalMoves;$("#memory-combo").textContent=`x${multiplier()}`;$("#memory-time").textContent=remaining?`${remaining}s`:"∞"};
    const revealAll=()=>{locked=true;cardNodes().forEach((node,index)=>{if(!done.has(index))node.classList.add("peek")});clearTimeout(peekTimer);peekTimer=setTimeout(()=>{cardNodes().forEach(node=>node.classList.remove("peek"));locked=false},1300)};
    const retrapPair=()=>{const solvedKeys=[...new Set([...done].map(index=>cards[index].key).filter(key=>cards.find(card=>card.key===key)?.type==="normal"))];if(!solvedKeys.length)return;const key=solvedKeys[Math.floor(Math.random()*solvedKeys.length)];cards.forEach((card,index)=>{if(card.key===key){done.delete(index);cardNodes()[index]?.classList.remove("done","open")}});$(".result").textContent="TRAP CARD • ONE SOLVED PAIR WAS HIDDEN AGAIN"};
    const applySpecial=card=>{if(card.type==="time"){if(remaining)remaining+=8;else totalScore+=80;$(".result").textContent=remaining?"TIME CARD • +8 SECONDS":"TIME CARD • +80 SCORE"}else if(card.type==="reveal"){$(".result").textContent="REVEAL CARD • BOARD SCAN";revealAll()}else if(card.type==="trap")retrapPair()};
    const completeLevel=()=>{stats.highestLevel=Math.max(stats.highestLevel||0,level);if(level>=3)return finish(true);clearInterval(timer);locked=true;totalScore+=level*250;level++;$(".result").textContent=`LEVEL CLEAR • PREPARING BOARD ${level}`;transitionTimer=setTimeout(()=>{if(!ended)loadLevel()},1000)};
    const finish=won=>{if(ended)return;ended=true;stopTimers();const seconds=Math.round((Date.now()-started)/1000);stats.bestScore=Math.max(stats.bestScore||0,totalScore);if(won)stats.highestLevel=Math.max(stats.highestLevel||0,3);if(won){stats.fewestMoves=Math.min(Number.isFinite(stats.fewestMoves)?stats.fewestMoves:Infinity,totalMoves);stats.fastestCompletion=Math.min(Number.isFinite(stats.fastestCompletion)?stats.fastestCompletion:Infinity,seconds)}setStage(`<div class="memory-report"><h3>${won?"MEMORY RUN COMPLETE 🏆":"MEMORY RUN ENDED"}</h3><div class="career-grid"><article><span>SCORE</span><b>${totalScore}</b></article><article><span>MOVES</span><b>${totalMoves}</b></article><article><span>TIME</span><b>${seconds}s</b></article><article><span>LEVEL</span><b>${stats.highestLevel||0}/3</b></article></div><p>BEST ${stats.bestScore} • FEWEST ${Number.isFinite(stats.fewestMoves)?stats.fewestMoves:"—"} • FASTEST ${Number.isFinite(stats.fastestCompletion)?`${stats.fastestCompletion}s`:"—"}</p><button id="memory-again" class="pixel-btn primary">NEW RUN</button></div>`);reward(Math.round(totalScore/100),Math.max(5,Math.round(totalScore/80)),{result:won?"win":"loss",score:totalScore});$("#memory-again").onclick=startMemory};
    const handleCard=index=>{if(locked||done.has(index)||open.includes(index)||ended)return;const node=cardNodes()[index];node.classList.add("open");open.push(index);if(open.length<2)return;totalMoves++;updateHud();const [a,b]=open;if(cards[a].key===cards[b].key){combo++;const gained=Math.round(100*multiplier());totalScore+=gained;done.add(a);done.add(b);cardNodes()[a].classList.add("done");cardNodes()[b].classList.add("done");const matched=cards[a];open=[];applySpecial(matched);updateHud();if(done.size===cards.length&&!locked)completeLevel();else if(done.size===cards.length)transitionTimer=setTimeout(()=>{if(!ended)completeLevel()},1400)}else{combo=0;locked=true;transitionTimer=setTimeout(()=>{cardNodes()[a]?.classList.remove("open");cardNodes()[b]?.classList.remove("open");open=[];locked=false;updateHud()},650)}};
    const loadLevel=()=>{stopTimers();locked=false;open=[];done=new Set();combo=0;const config=configs[level-1],pairs=config.cols*config.rows/2;remaining=config.time;cards=buildDeck(pairs,level);setStage(`<div class="game-score memory-hud">${difficulty.toUpperCase()} • LEVEL ${level}/3 • SCORE <b id="memory-score">${totalScore}</b> • MOVES <b id="memory-moves">${totalMoves}</b> • COMBO <b id="memory-combo">x1</b> • TIME <b id="memory-time">${remaining||"∞"}</b></div><div class="memory-grid memory-run-grid" style="--memory-cols:${config.cols}">${cards.map((card,index)=>`<button class="memory-card" data-i="${index}"><span>${card.icon}</span></button>`).join("")}</div><p class="result">Match pairs. Special pairs can change the run.</p>`);cardNodes().forEach(card=>card.onclick=()=>handleCard(Number(card.dataset.i)));if(remaining)timer=setInterval(()=>{remaining--;updateHud();if(remaining<=0)finish(false)},1000)};
    loadLevel();setActiveCleanup(()=>{ended=true;stopTimers()});
  }
}

GubuntuGames.register("memory",startMemory);
