"use strict";

function startPac(launchOptions={}){
  const layouts=[
    ["###############","#o....#.#....o#","#.##..#.#..##.#","#.............#","#.##.#####.##.#","#....#...#....#","####.#.#.#.####","#.............#","####.#.#.#.####","#....#...#....#","#.##.#####.##.#","#.............#","#.##..#.#..##.#","#o....#.#....o#","###############"],
    ["###############","#o............#","#.#####.#####.#","#.#.........#.#","#.#.###.###.#.#","#...#.....#...#","###.#.###.#.###","#.............#","###.#.###.#.###","#...#.....#...#","#.#.###.###.#.#","#.#.........#.#","#.#####.#####.#","#............o#","###############"],
    ["###############","#o..#.....#..o#","#.#.#.###.#.#.#","#.#...#.#...#.#","#.###.#.#.###.#","#.....#.#.....#","#####.#.#.#####","#.............#","#####.#.#.#####","#.....#.#.....#","#.###.#.#.###.#","#.#...#.#...#.#","#.#.#.###.#.#.#","#...#.....#...#","###############"],
    ["###############","#o....#.#....o#","###.#.#.#.#.###","#...#.....#...#","#.#####.#####.#","#.............#","#.###.###.###.#","#.#.........#.#","#.#.###.###.#.#","#.............#","#.#####.#####.#","#...#.....#...#","###.#.#.#.#.###","#.....#.#.....#","###############"],
    ["###############","#o............#","#.###.###.###.#","#...#.....#...#","###.#.###.#.###","#.....#.#.....#","#.###.#.#.###.#","#.............#","#.###.#.#.###.#","#.....#.#.....#","###.#.###.#.###","#...#.....#...#","#.###.###.###.#","#............o#","###############"]
  ];
  setStage(`<div class="game-score pac-hud">LEVEL <span id="pac-level">1</span>/5 • SCORE <span id="pac-score">0</span> • LIVES <span id="pac-lives">3</span> • POWER <span id="pac-power">—</span></div><div class="canvas-wrap"><canvas id="pac-canvas" class="arcade-canvas" width="450" height="450"></canvas></div>${directionPad()}<p class="result">Clear five neon mazes. Power pellets make every enemy vulnerable for 6 seconds.</p>`);
  const canvas=$("#pac-canvas"),ctx=canvas.getContext("2d"),tile=30,moves=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}],startedAt=performance.now();
  const ghostDefs=[{type:"hunter",color:"#ff3eb5",spawn:{x:13,y:13}},{type:"ambusher",color:"#31f5ff",spawn:{x:13,y:1}},{type:"wanderer",color:"#ff7043",spawn:{x:1,y:13}}];
  let level=1,lives=3,score=0,map=[],dots=0,player={x:1,y:1},dir={x:0,y:0},wanted={x:0,y:0},ghosts=[],mouth=0,powerUntil=0,powerEaten=0,bestPowerEaten=0,fruit=null,nextFruitAt=Date.now()+9000,invulnerableUntil=0,ended=false,timer=null,transitionTimer=null;
  const stats=currentPlayer.gameStats.pac||={plays:0,wins:0,losses:0,draws:0,best:null};
  const can=(p,v)=>map[p.y+v.y]?.[p.x+v.x]!=="#"&&map[p.y+v.y]?.[p.x+v.x]!==undefined;
  const distance=(x,y,target)=>Math.abs(x-target.x)+Math.abs(y-target.y);
  const restartTimer=()=>{clearInterval(timer);timer=setInterval(tick,Math.max(88,170*Math.pow(.91,level-1)))};
  const resetActors=()=>{player={x:1,y:1};dir={x:0,y:0};wanted={x:0,y:0};ghosts=ghostDefs.map(def=>({...def,x:def.spawn.x,y:def.spawn.y,last:{x:0,y:0}}));invulnerableUntil=Date.now()+1800};
  const loadLevel=()=>{map=layouts[(level-1)%layouts.length].map(row=>row.split(""));resetActors();map[player.y][player.x]=" ";ghosts.forEach(g=>{if(map[g.y]?.[g.x]!=="#")map[g.y][g.x]=" "});dots=map.flat().filter(cell=>cell==="."||cell==="o").length;fruit=null;nextFruitAt=Date.now()+8000;$("#pac-level").textContent=level;$("#pac-lives").textContent=lives;restartTimer();draw()};
  const openCells=()=>{const cells=[];for(let y=1;y<14;y++)for(let x=1;x<14;x++)if(map[y][x]!=="#"&&map[y][x]===" ")cells.push({x,y});return cells};
  const spawnFruit=()=>{const cells=openCells().filter(cell=>!ghosts.some(g=>g.x===cell.x&&g.y===cell.y)&&distance(cell.x,cell.y,player)>4);if(cells.length)fruit={...cells[Math.floor(Math.random()*cells.length)],until:Date.now()+6500};nextFruitAt=Date.now()+17000};
  const chooseGhostMove=g=>{let choices=moves.filter(v=>can(g,v));if(choices.length>1)choices=choices.filter(v=>v.x!==-g.last.x||v.y!==-g.last.y);if(!choices.length)return null;let target=player;if(g.type==="ambusher")target={x:player.x+dir.x*4,y:player.y+dir.y*4};if(g.type==="wanderer"&&Math.random()<.72)return choices[Math.floor(Math.random()*choices.length)];choices.sort((a,b)=>distance(g.x+a.x,g.y+a.y,target)-distance(g.x+b.x,g.y+b.y,target));return Math.random()<.82?choices[0]:choices[Math.floor(Math.random()*Math.min(2,choices.length))]};
  const drawGhost=g=>{const vulnerable=Date.now()<powerUntil,x=g.x*tile+15,y=g.y*tile+15;ctx.fillStyle=vulnerable?(Date.now()%350<175?"#365eff":"#f8f4ff"):g.color;ctx.beginPath();ctx.arc(x,y,11,Math.PI,0);ctx.lineTo(x+11,y+12);ctx.lineTo(x+5,y+7);ctx.lineTo(x,y+12);ctx.lineTo(x-5,y+7);ctx.lineTo(x-11,y+12);ctx.closePath();ctx.fill();ctx.fillStyle="#fff";ctx.fillRect(x-6,y-3,4,5);ctx.fillRect(x+2,y-3,4,5)};
  const draw=()=>{ctx.fillStyle="#050312";ctx.fillRect(0,0,450,450);for(let y=0;y<15;y++)for(let x=0;x<15;x++){const cell=map[y][x];if(cell==="#"){ctx.fillStyle=`hsl(${235+level*12} 62% 27%)`;ctx.fillRect(x*tile+2,y*tile+2,tile-4,tile-4);ctx.strokeStyle=level%2?"#31f5ff":"#8e5bff";ctx.strokeRect(x*tile+5,y*tile+5,tile-10,tile-10)}else if(cell==="."||cell==="o"){ctx.fillStyle=cell==="o"?"#ffe84c":"#f8f4ff";const r=cell==="o"?7:2;ctx.beginPath();ctx.arc(x*tile+15,y*tile+15,r,0,Math.PI*2);ctx.fill()}}if(fruit){ctx.fillStyle="#72ff77";ctx.font="22px monospace";ctx.textAlign="center";ctx.fillText("◆",fruit.x*tile+15,fruit.y*tile+22)}const px=player.x*tile+15,py=player.y*tile+15;ctx.fillStyle=Date.now()<invulnerableUntil&&Date.now()%220<110?"#fff":"#ffe84c";ctx.beginPath();const gap=mouth?.28:.08;ctx.arc(px,py,12,gap*Math.PI,(2-gap)*Math.PI);ctx.lineTo(px,py);ctx.fill();ghosts.forEach(drawGhost)};
  const persist=()=>{const survival=Math.round((performance.now()-startedAt)/1000);stats.highestLevel=Math.max(stats.highestLevel||0,level);stats.bestScore=Math.max(stats.bestScore||0,score);stats.longestSurvival=Math.max(stats.longestSurvival||0,survival);stats.mostEnemiesEaten=Math.max(stats.mostEnemiesEaten||0,bestPowerEaten);return survival};
  const finish=won=>{if(ended)return;ended=true;clearInterval(timer);clearTimeout(transitionTimer);const survival=persist();$(".result").innerHTML=`${won?"ALL FIVE MAZES CLEARED! 🏆":"RUN OVER"} • ${score} SCORE • ${survival}s<br>BEST LEVEL ${stats.highestLevel} • BEST SCORE ${stats.bestScore} • BEST POWER COMBO ${stats.mostEnemiesEaten}`;reward(Math.round(score/3)+(won?80:0),Math.max(8,Math.round(score/5)),{result:won?"win":"loss",score})};
  const loseLife=()=>{if(Date.now()<invulnerableUntil)return;lives--;$("#pac-lives").textContent=lives;if(lives<=0)return finish(false);$(".result").textContent=`LIFE LOST • ${lives} REMAINING`;resetActors();draw()};
  const clearLevel=()=>{score+=level*40;if(level>=5)return finish(true);clearInterval(timer);level++;$(".result").textContent=`MAZE CLEAR • LEVEL ${level} ENEMIES +${Math.round((1-Math.pow(.91,level-1))*100)}% SPEED`;transitionTimer=setTimeout(()=>{if(!ended)loadLevel()},1100)};
  const tick=()=>{const now=Date.now();if(can(player,wanted))dir=wanted;if(can(player,dir)){player.x+=dir.x;player.y+=dir.y}const cell=map[player.y][player.x];if(cell==="."||cell==="o"){map[player.y][player.x]=" ";score+=cell==="o"?5:1;dots--;if(cell==="o"){powerUntil=now+6000;powerEaten=0}$("#pac-score").textContent=score;if(!dots)return clearLevel()}if(now>=nextFruitAt&&!fruit)spawnFruit();if(fruit&&now>fruit.until)fruit=null;if(fruit&&player.x===fruit.x&&player.y===fruit.y){score+=50+level*10;fruit=null;$("#pac-score").textContent=score;$(".result").textContent="FRUIT BONUS!"}ghosts.forEach(g=>{const move=chooseGhostMove(g);if(move){g.x+=move.x;g.y+=move.y;g.last=move}});ghosts.forEach(g=>{if(g.x!==player.x||g.y!==player.y)return;if(now<powerUntil){score+=20*(powerEaten+1);powerEaten++;bestPowerEaten=Math.max(bestPowerEaten,powerEaten);g.x=g.spawn.x;g.y=g.spawn.y;$("#pac-score").textContent=score}else loseLife()});if(now>=powerUntil)powerEaten=0;$("#pac-power").textContent=now<powerUntil?`${Math.ceil((powerUntil-now)/1000)}s • ${powerEaten} EATEN`:"—";mouth=1-mouth;draw()};
  const unbind=bindDirections(d=>{wanted={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[d]});loadLevel();setActiveCleanup(()=>{ended=true;clearInterval(timer);clearTimeout(transitionTimer);unbind()});
}

GubuntuGames.register("pac",startPac);
