"use strict";

function startReaction(launchOptions={}){
  setStage(`<div class="reaction-intro"><p class="eyebrow">FIVE-EVENT SKILL TEST</p><h3>TURBO REACTION CIRCUIT</h3><ol><li>Green signal</li><li>Direction key</li><li>Color conflict</li><li>Fake red signal</li><li>Moving target</li></ol><button id="reaction-start" class="pixel-btn primary">START FIVE-ROUND TEST</button><p class="result">Early −250 • Wrong −150 • Missed event 0</p></div>`);
  const timers=new Set(),results=[];let round=0,totalScore=0,falseStarts=0,roundActive=false,signalLive=false,startedAt=0,ended=false;
  const schedule=(fn,delay)=>{const id=setTimeout(()=>{timers.delete(id);fn()},delay);timers.add(id);return id},clearTimers=()=>{timers.forEach(clearTimeout);timers.clear()};
  const eventNames=["GREEN SIGNAL","DIRECTION SIGNAL","COLOR CONFLICT","FAKE SIGNAL","MOVING TARGET"];
  const scoreRound=(ms,penalty=0)=>Math.max(0,1000-ms*2)-penalty;
  const updateHeader=()=>{const score=$("#reaction-total");if(score)score.textContent=totalScore;const label=$("#reaction-round");if(label)label.textContent=`${round+1}/5`};
  const completeRound=(ms=null,penalty=0,note="")=>{if(!roundActive)return;roundActive=false;signalLive=false;clearTimers();const roundScore=ms==null?0:scoreRound(ms,penalty);totalScore+=roundScore;if(penalty===250)falseStarts++;results.push({round:round+1,type:eventNames[round],ms,penalty,score:roundScore,note});const result=$("#reaction-feedback");if(result)result.textContent=`${note} • ${ms==null?"NO TIME":`${Math.round(ms)} ms`} • ${roundScore} POINTS`;round++;if(round>=5)return schedule(finish,900);schedule(runRound,900)};
  const armTimeout=()=>schedule(()=>completeRound(null,0,"MISSED EVENT"),2500);
  const early=()=>completeRound(0,250,"FALSE START −250");
  const showSignal=(content,className="go")=>{signalLive=true;startedAt=performance.now();const arena=$("#reaction-arena");arena.className=`reaction-arena ${className}`;arena.innerHTML=content;armTimeout()};
  const runRound=()=>{if(ended)return;roundActive=true;signalLive=false;setStage(`<div class="game-score">ROUND <b id="reaction-round">${round+1}/5</b> • TOTAL <b id="reaction-total">${totalScore}</b></div><h3>${eventNames[round]}</h3><div id="reaction-arena" class="reaction-arena waiting">GET READY…</div><p id="reaction-feedback" class="result">Wait for the event.</p>`);const arena=$("#reaction-arena"),delay=1100+Math.random()*1700;
    if(round===0){arena.onclick=()=>signalLive?completeRound(performance.now()-startedAt,0,"GREEN HIT"):early();schedule(()=>showSignal("CLICK NOW","go"),delay)}
    else if(round===1){const directions=[{key:"ArrowUp",label:"↑"},{key:"ArrowDown",label:"↓"},{key:"ArrowLeft",label:"←"},{key:"ArrowRight",label:"→"}],target=directions[Math.floor(Math.random()*directions.length)];arena.dataset.targetKey=target.key;schedule(()=>showSignal(`<span class="reaction-arrow">${target.label}</span><small>PRESS THE ARROW KEY</small>`,"direction"),delay)}
    else if(round===2){const colors=[{id:"red",label:"RED",hex:"#ff3e5f"},{id:"green",label:"GREEN",hex:"#2ce58b"},{id:"blue",label:"BLUE",hex:"#31a8ff"}],word=colors[Math.floor(Math.random()*colors.length)],display=colors.filter(c=>c.id!==word.id)[Math.floor(Math.random()*2)];schedule(()=>{showSignal(`<b style="color:${display.hex}">${word.label}</b><small>CLICK THE BUTTON MATCHING THE WORD</small><div class="reaction-colors">${colors.map(c=>`<button data-color="${c.id}" style="--signal:${c.hex}">${c.label}</button>`).join("")}</div>`,"conflict");$$('[data-color]').forEach(button=>button.onclick=e=>{e.stopPropagation();const ms=performance.now()-startedAt;completeRound(ms,button.dataset.color===word.id?0:150,button.dataset.color===word.id?"COLOR MATCH":"WRONG COLOR −150")})},delay);arena.onclick=()=>{if(!signalLive)early()}}
    else if(round===3){arena.onclick=()=>signalLive?completeRound(performance.now()-startedAt,0,"GREEN CONFIRMED"):early();schedule(()=>{arena.className="reaction-arena fake";arena.textContent="RED • DO NOT CLICK";schedule(()=>showSignal("GREEN • CLICK NOW","go"),900+Math.random()*1000)},delay)}
    else{arena.onclick=e=>{if(!signalLive)return early();if(!e.target.closest("#reaction-target"))completeRound(performance.now()-startedAt,150,"WRONG TARGET −150")};schedule(()=>{const x=8+Math.random()*76,y=10+Math.random()*68;showSignal(`<button id="reaction-target" class="reaction-target" style="left:${x}%;top:${y}%" aria-label="Moving target"></button>`,"target-field");$("#reaction-target").onclick=e=>{e.stopPropagation();completeRound(performance.now()-startedAt,0,"TARGET HIT")}},delay)}updateHeader()};
  const keyHandler=e=>{if(ended||round!==1||!roundActive)return;if(!signalLive)return early();const target=$("#reaction-arena")?.dataset.targetKey,ms=performance.now()-startedAt;completeRound(ms,e.key===target?0:150,e.key===target?"CORRECT DIRECTION":"WRONG KEY −150")};
  const finish=()=>{if(ended)return;ended=true;clearTimers();window.removeEventListener("keydown",keyHandler);const valid=results.filter(item=>item.ms!=null&&item.penalty<250),average=valid.length?Math.round(valid.reduce((sum,item)=>sum+item.ms,0)/valid.length):0,best=valid.length?Math.round(Math.min(...valid.map(item=>item.ms))):0,maximum=5000,rating=totalScore>=4500?"S":totalScore>=3600?"A":totalScore>=2700?"B":totalScore>=1800?"C":"D",stats=currentPlayer.gameStats.reaction||={plays:0,wins:0,losses:0,draws:0,best:null};stats.bestAverage=average?Math.min(Number.isFinite(stats.bestAverage)?stats.bestAverage:Infinity,average):stats.bestAverage;stats.fastestReaction=best?Math.min(Number.isFinite(stats.fastestReaction)?stats.fastestReaction:Infinity,best):stats.fastestReaction;stats.highestScore=Math.max(stats.highestScore||0,totalScore);if(falseStarts===0&&results.every(item=>item.ms!=null&&item.penalty===0))stats.perfectRuns=(stats.perfectRuns||0)+1;setStage(`<div class="reaction-report"><h3>REACTION RATING: <strong>${rating}</strong></h3><div class="career-grid"><article><span>AVERAGE REACTION</span><b>${average||"—"}${average?" ms":""}</b></article><article><span>BEST ROUND</span><b>${best||"—"}${best?" ms":""}</b></article><article><span>FALSE STARTS</span><b>${falseStarts}</b></article><article><span>TOTAL SCORE</span><b>${totalScore}/${maximum}</b></article></div><section>${results.map(item=>`<p><b>${item.round}. ${item.type}</b><span>${item.ms==null?"MISSED":`${Math.round(item.ms)} ms`} • ${item.score}</span></p>`).join("")}</section><button id="reaction-again" class="pixel-btn primary">RUN AGAIN</button></div>`);reward(Math.max(0,Math.round(totalScore/120)),Math.max(5,Math.round(totalScore/100)),{result:rating==="S"||rating==="A"?"win":"loss",score:totalScore});$("#reaction-again").onclick=startReaction};
  window.addEventListener("keydown",keyHandler);$("#reaction-start").onclick=runRound;setActiveCleanup(()=>{ended=true;clearTimers();window.removeEventListener("keydown",keyHandler)});
}

GubuntuGames.register("reaction",startReaction);
