"use strict";

function startSnake(launchOptions=null){
  const preselectedMode=typeof launchOptions==="string"?launchOptions:launchOptions?.mode;
  const stats=currentPlayer.gameStats.snake||={plays:0,wins:0,losses:0,draws:0,best:null};stats.modes||={};
  if(["classic","survival","time"].includes(preselectedMode))return beginSnake(preselectedMode);
  setStage(`<div class="arcade-mode-select"><p class="eyebrow">NEON SNAKE PROTOCOL</p><h3>CHOOSE RUN MODE</h3><div class="arcade-mode-grid"><button data-snake-mode="classic"><b>CLASSIC</b><small>Traditional walls, escalating speed and obstacles.</small></button><button data-snake-mode="survival"><b>SURVIVAL</b><small>Faster hazards and aggressive obstacle growth.</small></button><button data-snake-mode="time"><b>TIME ATTACK</b><small>Score as much as possible in 60 seconds.</small></button></div><div class="snake-records">${["classic","survival","time"].map(mode=>`<span>${mode.toUpperCase()}<b>${stats.modes[mode]?.bestScore||0}</b></span>`).join("")}</div></div>`);
  $$('[data-snake-mode]').forEach(button=>button.onclick=()=>beginSnake(button.dataset.snakeMode));
  function beginSnake(mode){
    setStage(`<div class="game-score snake-hud"><span>${mode.toUpperCase()}</span> • SCORE <b id="snake-score">0</b> • COMBO <b id="snake-combo">x1</b> • FOOD <b id="snake-foods">0</b><span id="snake-time"></span></div><div class="canvas-wrap"><canvas id="snake-canvas" class="arcade-canvas" width="400" height="400"></canvas><div id="snake-upgrade" class="arcade-upgrade" hidden></div></div>${directionPad()}<p class="result">Normal, golden and unstable glitch food are active.</p>`);
    const canvas=$("#snake-canvas"),ctx=canvas.getContext("2d"),size=20,cells=20,started=Date.now(),run={slowCurve:0,doubleScore:0,shortGrowth:0,shield:0,magnet:0};
    const upgradeDefs=[{id:"slowCurve",name:"COOLANT",desc:"Speed increases 45% more slowly."},{id:"doubleScore",name:"DOUBLE BITE",desc:"All food score is doubled."},{id:"shortGrowth",name:"COMPACT BODY",desc:"Only every second food grows the body."},{id:"shield",name:"PHASE SHIELD",desc:"Survive one collision."},{id:"magnet",name:"FOOD MAGNET",desc:"Nearby food drifts toward your head."}];
    let snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dir={x:1,y:0},next={x:1,y:0},food=null,obstacles=[],score=0,foods=0,combo=0,lastFoodAt=0,ended=false,timer=null,growthToggle=false,nextObstacle=mode==="survival"?10:16,glitchSpeedUntil=0;
    const occupied=(x,y)=>snake.some(p=>p.x===x&&p.y===y)||obstacles.some(p=>p.x===x&&p.y===y);
    const randomCell=()=>{let cell,guard=0;do{cell={x:Math.floor(Math.random()*cells),y:Math.floor(Math.random()*cells)};guard++}while((occupied(cell.x,cell.y)||food&&food.x===cell.x&&food.y===cell.y)&&guard<500);return cell};
    const placeFood=()=>{const roll=Math.random(),type=roll<.7?"normal":roll<.88?"golden":"glitch";food={...randomCell(),type,expires:type==="golden"?Date.now()+5000:0}};
    const delay=()=>{const base=mode==="survival"?105:mode==="time"?118:130,curve=run.slowCurve?.55:1,glitch=Date.now()<glitchSpeedUntil?.72:1;return Math.max(mode==="survival"?48:55,(base-foods*2.4*curve)*glitch)};
    const restart=()=>{clearInterval(timer);if(!ended)timer=setInterval(tick,delay())};
    const addObstacles=()=>{const amount=mode==="survival"?3:2;for(let i=0;i<amount;i++){const cell=randomCell();if(Math.abs(cell.x-snake[0].x)+Math.abs(cell.y-snake[0].y)>4)obstacles.push(cell)}nextObstacle+=mode==="survival"?10:16};
    const updateHud=()=>{$("#snake-score").textContent=score;$("#snake-foods").textContent=foods;$("#snake-combo").textContent=`x${(1+Math.min(2,Math.floor(combo/3)*.25)).toFixed(combo>=3?2:0)}`;const time=$("#snake-time");if(time)time.textContent=mode==="time"?` • TIME ${Math.max(0,60-Math.floor((Date.now()-started)/1000))}`:` • SHIELD ${run.shield}`};
    const draw=()=>{ctx.fillStyle="#050312";ctx.fillRect(0,0,400,400);ctx.strokeStyle="#17103c";for(let i=0;i<cells;i++){ctx.beginPath();ctx.moveTo(i*size,0);ctx.lineTo(i*size,400);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*size);ctx.lineTo(400,i*size);ctx.stroke()}obstacles.forEach(p=>{ctx.fillStyle="#8e5bff";ctx.fillRect(p.x*size+2,p.y*size+2,16,16);ctx.fillStyle="#ff3eb5";ctx.fillRect(p.x*size+6,p.y*size+6,8,8)});if(food){ctx.fillStyle={normal:"#ff3eb5",golden:"#ffe84c",glitch:"#72ff77"}[food.type];ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=food.type==="normal"?5:14;ctx.fillRect(food.x*size+4,food.y*size+4,12,12);if(food.type==="glitch"){ctx.fillStyle="#fff";ctx.fillRect(food.x*size+8,food.y*size+2,4,16)}ctx.shadowBlur=0}snake.forEach((p,i)=>{ctx.fillStyle=i?"#31f5ff":"#ffe84c";ctx.fillRect(p.x*size+2,p.y*size+2,16,16)});if(run.shield){ctx.strokeStyle="#fff";ctx.beginPath();ctx.arc(snake[0].x*size+10,snake[0].y*size+10,13,0,Math.PI*2);ctx.stroke()}};
    const finish=(timed=false)=>{if(ended)return;ended=true;clearInterval(timer);const seconds=Math.round((Date.now()-started)/1000),record=stats.modes[mode]||={bestScore:0,longest:0,mostFood:0};record.bestScore=Math.max(record.bestScore,score);record.longest=Math.max(record.longest,seconds);record.mostFood=Math.max(record.mostFood,foods);stats.modes[mode]=record;$(".result").innerHTML=`${timed?"TIME!":"GAME OVER"} • ${score} SCORE • ${foods} FOOD • ${seconds}s<br>${mode.toUpperCase()} RECORD ${record.bestScore}`;reward(score*2,Math.max(5,score),{result:timed?"win":"loss",score})};
    const shieldCrash=()=>{if(!run.shield)return false;run.shield--;snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];dir={x:1,y:0};next={x:1,y:0};$(".result").textContent="PHASE SHIELD SAVED THE RUN";return true};
    const applyGlitch=()=>{const effects=[()=>{score+=8;$(".result").textContent="GLITCH: BONUS CACHE +8"},()=>{score=Math.max(0,score-5);$(".result").textContent="GLITCH: SCORE CORRUPTED -5"},()=>{snake.splice(Math.max(3,snake.length-3));$(".result").textContent="GLITCH: BODY COMPRESSED"},()=>{glitchSpeedUntil=Date.now()+6000;$(".result").textContent="GLITCH: OVERDRIVE 6s"},()=>{run.shield++;$(".result").textContent="GLITCH: FREE SHIELD"}];effects[Math.floor(Math.random()*effects.length)]()};
    const offerUpgrade=()=>{clearInterval(timer);const host=$("#snake-upgrade"),picks=[...upgradeDefs].sort(()=>Math.random()-.5).slice(0,3);host.hidden=false;host.innerHTML=`<b>RUN UPGRADE • CHOOSE ONE</b>${picks.map(up=>`<button data-snake-up="${up.id}"><strong>${up.name}</strong><small>${up.desc}</small></button>`).join("")}`;host.querySelectorAll("[data-snake-up]").forEach(button=>button.onclick=()=>{const id=button.dataset.snakeUp;if(id==="shield")run.shield++;else run[id]=1;host.hidden=true;restart();updateHud();draw()})};
    const attractFood=()=>{if(!run.magnet||!food)return;const head=snake[0],dx=head.x-food.x,dy=head.y-food.y;if(Math.abs(dx)+Math.abs(dy)>5)return;const candidates=Math.abs(dx)>Math.abs(dy)?[{x:food.x+Math.sign(dx),y:food.y},{x:food.x,y:food.y+Math.sign(dy)}]:[{x:food.x,y:food.y+Math.sign(dy)},{x:food.x+Math.sign(dx),y:food.y}];const nextCell=candidates.find(p=>p.x>=0&&p.y>=0&&p.x<cells&&p.y<cells&&!occupied(p.x,p.y));if(nextCell){food.x=nextCell.x;food.y=nextCell.y}};
    const eat=()=>{const now=Date.now();combo=now-lastFoodAt<4000?combo+1:1;lastFoodAt=now;foods++;const comboMult=1+Math.min(2,Math.floor(combo/3)*.25),base=food.type==="golden"?3:1;score+=Math.round(base*(run.doubleScore?2:1)*comboMult);if(food.type==="glitch")applyGlitch();growthToggle=!growthToggle;const shouldGrow=food.type==="normal"&&(!run.shortGrowth||growthToggle);if(!shouldGrow)snake.pop();placeFood();if(score>=nextObstacle)addObstacles();updateHud();draw();restart();if(foods%5===0)offerUpgrade()};
    const tick=()=>{if(mode==="time"&&Date.now()-started>=60000)return finish(true);if(food?.expires&&Date.now()>food.expires){$(".result").textContent="GOLDEN FOOD EXPIRED";placeFood()}attractFood();dir=next;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y},collision=head.x<0||head.y<0||head.x>=cells||head.y>=cells||snake.some(p=>p.x===head.x&&p.y===head.y)||obstacles.some(p=>p.x===head.x&&p.y===head.y);if(collision){if(shieldCrash()){updateHud();draw();return}return finish(false)}snake.unshift(head);if(food&&head.x===food.x&&head.y===food.y)eat();else snake.pop();if(Date.now()-lastFoodAt>4000)combo=0;updateHud();draw()};
    const unbind=bindDirections(d=>{const v={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[d];if(v.x!==-dir.x||v.y!==-dir.y)next=v});placeFood();updateHud();draw();restart();setActiveCleanup(()=>{ended=true;clearInterval(timer);unbind()});
  }
}

GubuntuGames.register("snake",startSnake);
