"use strict";

function startBilliards(launchOptions={}){
  const mode=["ai","ladder","local"].includes(launchOptions.mode)?launchOptions.mode:"ai",difficulty=["easy","normal","hard"].includes(launchOptions.difficulty)?launchOptions.difficulty:"normal",theme=["neon","sunset","arctic","cosmic"].includes(launchOptions.theme)?launchOptions.theme:"neon",ladderLevels=["easy","normal","hard","champion"],ladderNames={easy:"ROOKIE",normal:"CLUB PLAYER",hard:"PRO",champion:"NEON CHAMPION"},ladderIndex=Math.max(0,Math.min(3,Number(launchOptions.ladderIndex)||0));
  let aiLevel=mode==="ladder"?ladderLevels[ladderIndex]:difficulty;
  const isAi=mode!=="local",opponentName=()=>ladderNames[aiLevel]||`${aiLevel.toUpperCase()} AI`;
  const arenaThemes={
    neon:{name:"NEON CLUB",felt:"#073f38",felt2:"#0b5b4d",rail:"#6b3218",frame:"#17102d",accent:"#2de2a6",glow:"#31f5ff",cue:"#e2ad72"},
    sunset:{name:"SUNSET ROOFTOP",felt:"#54213e",felt2:"#7d2947",rail:"#d17237",frame:"#27152f",accent:"#ffb347",glow:"#ff4f9a",cue:"#ffe0a3"},
    arctic:{name:"ARCTIC CIRCUIT",felt:"#154b65",felt2:"#1f7591",rail:"#b8e8f4",frame:"#10263c",accent:"#b9f7ff",glow:"#57d7ff",cue:"#ecfbff"},
    cosmic:{name:"COSMIC VOID",felt:"#22134f",felt2:"#38216f",rail:"#563b8d",frame:"#09051d",accent:"#c982ff",glow:"#ff4fdd",cue:"#f0c9ff"}
  },arena=arenaThemes[theme];
  const stats=currentPlayer.gameStats.billiards||={plays:0,wins:0,losses:0,draws:0,best:null};
  stats.plays=(stats.plays||0)+1;stats.opponents||={};saveData();
  setStage(`<section class="billiards-game pool-theme-${theme}" style="--pool-accent:${arena.accent};--pool-glow:${arena.glow}"><div class="billiards-scoreboard"><article id="pool-player-0"><small>PLAYER 1</small><b id="pool-name-0">YOU</b><span id="pool-group-0">OPEN TABLE</span></article><div><strong id="pool-turn">PLAYER 1 TURN</strong><small id="pool-message">Aim freely, then drag straight back and release.</small></div><article id="pool-player-1"><small>PLAYER 2</small><b id="pool-name-1">${isAi?opponentName():"PLAYER 2"}</b><span id="pool-group-1">OPEN TABLE</span></article></div><div class="billiards-arena-label"><span>${arena.name}${mode==="ladder"?` • LADDER ${ladderIndex+1}/4`:""}</span><small>LEGAL 8-BALL • BALL IN HAND • SPIN + DEFLECTION PHYSICS</small></div><div id="pool-call-pocket" class="pool-call-pocket" hidden><span>CALL THE 8-BALL POCKET</span>${["TOP LEFT","TOP MIDDLE","TOP RIGHT","BOTTOM LEFT","BOTTOM MIDDLE","BOTTOM RIGHT"].map((label,index)=>`<button type="button" data-pool-pocket="${index}">${index+1}<small>${label}</small></button>`).join("")}</div><div class="billiards-table-wrap"><canvas id="billiards-canvas" width="900" height="500" aria-label="Interactive ${arena.name.toLowerCase()} billiards table"></canvas><i id="pool-lock-indicator">AIM FREE</i></div><div class="billiards-controls"><label><span>SHOT POWER</span><input id="pool-power" type="range" min="10" max="100" value="58"><b id="pool-power-value">58%</b></label><div class="pool-spin-control"><small>CUE CONTACT</small><canvas id="pool-spin-pad" width="100" height="100" aria-label="Cue ball spin contact selector"></canvas><b id="pool-spin-label">CENTER</b></div><div class="pool-fine-aim"><button type="button" data-pool-nudge="-1" aria-label="Aim left by 0.25 degrees">◀ 0.25°</button><b id="pool-angle">0.00°</b><button type="button" data-pool-nudge="1" aria-label="Aim right by 0.25 degrees">0.25° ▶</button></div><button id="pool-shoot" class="pixel-btn primary">SHOOT • SPACE</button></div><p class="billiards-help">After a foul, place the cue ball manually and confirm with click or Space. Call a pocket before the 8-ball. Drag the cue contact point for topspin, draw, or side English.</p></section>`);
  const canvas=$("#billiards-canvas"),ctx=canvas.getContext("2d"),spinCanvas=$("#pool-spin-pad"),spinCtx=spinCanvas.getContext("2d"),powerInput=$("#pool-power"),shootButton=$("#pool-shoot"),nudgeButtons=$$("[data-pool-nudge]"),pocketButtons=$$("[data-pool-pocket]"),W=900,H=500,R=12.5,rail={l:43,r:857,t:43,b:457};
  const pockets=[{x:43,y:43},{x:450,y:38},{x:857,y:43},{x:43,y:457},{x:450,y:462},{x:857,y:457}],colors=["#fff","#ffe84c","#2f6bff","#ff4b3e","#9b4dff","#ff8b2c","#2de2a6","#8c263b","#151522","#ffe84c","#2f6bff","#ff4b3e","#9b4dff","#ff8b2c","#2de2a6","#8c263b"];
  const balls=[],timeouts=new Set();let current=0,groups=[null,null],aimAngle=0,aimTargetAngle=0,power=58,shotActive=false,shotPotted=[],shotTarget="open",scratch=false,firstHit=null,ended=false,raf=0,last=performance.now(),accumulator=0,shots=0,aimLocked=false,dragging=false,dragStart=null,dragDistance=0,ballInHand=false,placement={x:235,y:250},placementValid=true,railAfterContact=false,objectBallPotted=false,breakShot=true,railContactCount=0,calledPocket=null,shotCalledPocket=null,eightPocket=null,spinX=0,spinY=0,spinDragging=false,shotSpinX=0,shotSpinY=0,shotDirectionX=1,shotDirectionY=0,spinApplied=false,turnsTaken=[0,0];
  const schedule=(fn,ms)=>{const id=setTimeout(()=>{timeouts.delete(id);fn()},ms);timeouts.add(id);return id};
  const makeBall=(id,x,y)=>({id,x,y,vx:0,vy:0,spinX:0,rotation:0,active:true});
  balls.push(makeBall(0,235,250));
  const rack=[1,9,2,10,8,3,11,4,12,5,13,6,14,7,15],gap=R*2+.8,startX=645;let n=0;
  for(let row=0;row<5;row++)for(let col=0;col<=row;col++){const id=rack[n++];balls.push(makeBall(id,startX+row*gap*.87,250+(col-row/2)*gap));}
  const cue=()=>balls[0],groupOf=id=>id>=1&&id<=7?"solids":id>=9&&id<=15?"stripes":null,remaining=group=>balls.filter(ball=>ball.active&&groupOf(ball.id)===group).length;
  const humanTurn=()=>mode==="local"||current===0,anyMoving=()=>balls.some(ball=>ball.active&&Math.hypot(ball.vx,ball.vy)>.045);
  const playerName=index=>index===0?"PLAYER 1":isAi?opponentName():"PLAYER 2";
  const setMessage=text=>{$("#pool-message").textContent=text};
  const normalizeAngle=value=>Math.atan2(Math.sin(value),Math.cos(value));
  const angleDelta=(from,to)=>normalizeAngle(to-from);
  const updateAngleReadout=()=>{const readout=$("#pool-angle");if(readout)readout.textContent=`${((aimAngle*180/Math.PI+360)%360).toFixed(2)}°`};
  const setAimAngle=(value,immediate=false)=>{aimTargetAngle=normalizeAngle(value);if(immediate)aimAngle=aimTargetAngle;updateAngleReadout()};
  const nudgeAim=(direction,degrees=.25)=>{if(ended||shotActive||!humanTurn())return;setAimAngle(aimTargetAngle+direction*degrees*Math.PI/180,true);setAimLock(true);setMessage(`PRECISION AIM • ${((aimAngle*180/Math.PI+360)%360).toFixed(2)}°`);updateHud()};
  const setAimLock=locked=>{aimLocked=locked;const indicator=$("#pool-lock-indicator");if(indicator){indicator.textContent=locked?"AIM LOCKED":"AIM FREE";indicator.classList.toggle("locked",locked)}canvas.classList.toggle("aim-locked",locked)};
  const updateHud=()=>{for(let i=0;i<2;i++){const group=groups[i],left=group?remaining(group):7;$("#pool-group-"+i).textContent=group?`${group.toUpperCase()} • ${left} LEFT`:"OPEN TABLE";$("#pool-player-"+i).classList.toggle("active",i===current)}$("#pool-turn").textContent=ballInHand?`${playerName(current)} • BALL IN HAND`:`${playerName(current)} TURN`;const needsCall=legalFirstTarget()==="eight"&&humanTurn()&&!shotActive&&!ballInHand,controlsDisabled=ended||shotActive||ballInHand||!humanTurn();powerInput.disabled=controlsDisabled;shootButton.disabled=controlsDisabled||(needsCall&&calledPocket===null);nudgeButtons.forEach(button=>button.disabled=controlsDisabled);spinCanvas.classList.toggle("disabled",controlsDisabled);const callPanel=$("#pool-call-pocket");callPanel.hidden=!needsCall;pocketButtons.forEach(button=>button.classList.toggle("active",Number(button.dataset.poolPocket)===calledPocket));shootButton.textContent=needsCall&&calledPocket===null?"CALL A POCKET":aimLocked?"SHOOT LOCKED ANGLE":"SHOOT • SPACE";updateAngleReadout()};
  const validCuePlacement=(x,y)=>x>=rail.l+R&&x<=rail.r-R&&y>=rail.t+R&&y<=rail.b-R&&!pockets.some(pocket=>Math.hypot(x-pocket.x,y-pocket.y)<30)&&balls.every(ball=>ball.id===0||!ball.active||Math.hypot(ball.x-x,ball.y-y)>=R*2+1);
  const findLegalPlacement=(preferred={x:235,y:250})=>{if(validCuePlacement(preferred.x,preferred.y))return preferred;for(let radius=20;radius<330;radius+=20)for(let angle=0;angle<Math.PI*2;angle+=Math.PI/12){const point={x:preferred.x+Math.cos(angle)*radius,y:preferred.y+Math.sin(angle)*radius};if(validCuePlacement(point.x,point.y))return point}return{x:235,y:250}};
  const confirmCuePlacement=()=>{if(!ballInHand||!placementValid)return false;const ball=cue();ball.active=true;ball.x=placement.x;ball.y=placement.y;ball.vx=ball.vy=0;ball.spinX=0;ballInHand=false;setMessage("CUE BALL PLACED • AIM YOUR SHOT");updateHud();if(!humanTurn())schedule(aiShoot,500);return true};
  const beginBallInHand=()=>{const ball=cue();ball.active=false;ball.vx=ball.vy=0;placement=findLegalPlacement();placementValid=true;ballInHand=true;setAimLock(false);setMessage(humanTurn()?"BALL IN HAND • MOVE THE CUE BALL AND CLICK TO PLACE":"AI HAS BALL IN HAND");updateHud();if(!humanTurn())schedule(()=>{placement=findLegalPlacement({x:250+Math.random()*80,y:190+Math.random()*120});placementValid=true;confirmCuePlacement()},550)};
  const finish=winner=>{if(ended)return;ended=true;shotActive=false;ballInHand=false;timeouts.forEach(clearTimeout);timeouts.clear();const playerWon=winner===0,recordKey=isAi?aiLevel:"local",record=stats.opponents[recordKey]||={wins:0,losses:0};if(playerWon)record.wins++;else record.losses++;stats.opponents[recordKey]=record;stats.currentWinStreak=playerWon?(stats.currentWinStreak||0)+1:0;stats.highestWinStreak=Math.max(stats.highestWinStreak||0,stats.currentWinStreak);const breakAndRun=playerWon&&isAi&&turnsTaken[1]===0;if(breakAndRun)stats.breakAndRuns=(stats.breakAndRuns||0)+1;if(playerWon)stats.fewestShots=Math.min(stats.fewestShots||Infinity,turnsTaken[0]||shots);stats.best=Number.isFinite(stats.fewestShots)?stats.fewestShots:null;const ladderContinues=mode==="ladder"&&playerWon&&ladderIndex<3,ladderCleared=mode==="ladder"&&playerWon&&ladderIndex===3;if(ladderCleared)stats.ladderClears=(stats.ladderClears||0)+1;saveData();updateHud();setMessage(`${playerName(winner)} WINS THE TABLE`);schedule(()=>{const nextLabel=ladderContinues?`NEXT: ${ladderNames[ladderLevels[ladderIndex+1]]}`:mode==="ladder"&&!playerWon?"RESTART LADDER":"RACK AGAIN";setStage(`<div class="billiards-report"><div class="big-icon">🎱</div><p class="eyebrow">${ladderCleared?"NEON LADDER CONQUERED":mode==="ladder"?`LADDER ${ladderIndex+1}/4 COMPLETE`:"8-BALL MATCH COMPLETE"}</p><h3>${playerName(winner)} WINS</h3><div class="career-grid"><article><span>OPPONENT</span><b>${isAi?opponentName():"LOCAL 2P"}</b></article><article><span>YOUR SHOTS</span><b>${turnsTaken[0]}</b></article><article><span>BREAK & RUN</span><b>${breakAndRun?"YES":"NO"}</b></article><article><span>WIN STREAK</span><b>${stats.currentWinStreak||0}</b></article></div><p>RECORD ${record.wins}W / ${record.losses}L • BEST ${Number.isFinite(stats.fewestShots)?stats.fewestShots+" SHOTS":"—"} • LADDER CLEARS ${stats.ladderClears||0}</p><button id="pool-again" class="pixel-btn primary">${nextLabel}</button></div>`);reward(playerWon?55+(mode==="ladder"?ladderIndex*15:0):8,playerWon?40:10,{result:playerWon?"win":"loss",score:playerWon?Math.max(1,40-turnsTaken[0]):0,countGamePlay:false});$("#pool-again").onclick=()=>startBilliards({...launchOptions,mode,ladderIndex:ladderContinues?ladderIndex+1:mode==="ladder"&&!playerWon?0:ladderIndex})},900)};
  const legalFirstTarget=()=>{const group=groups[current];return group?(remaining(group)?group:"eight"):"open"};
  const resolveShot=()=>{shotActive=false;setAimLock(false);const shooter=current,eightPotted=shotPotted.includes(8),target=shotTarget,firstGroup=groupOf(firstHit),wrongFirst=!firstHit||(target==="eight"?firstHit!==8:target==="open"?firstHit===8:firstGroup!==target),illegalBreak=breakShot&&!objectBallPotted&&railContactCount<4,foul=scratch||wrongFirst||(!objectBallPotted&&!railAfterContact)||illegalBreak,firstObject=shotPotted.find(id=>id!==0&&id!==8);if(eightPotted){const legal=target==="eight"&&!foul&&shotCalledPocket!==null&&eightPocket===shotCalledPocket;return finish(legal?shooter:1-shooter)}if(!foul&&!groups[0]&&firstObject){groups[shooter]=groupOf(firstObject);groups[1-shooter]=groups[shooter]==="solids"?"stripes":"solids"}const ownPotted=shotPotted.some(id=>groupOf(id)===groups[shooter]);calledPocket=null;shotPotted=[];scratch=false;firstHit=null;objectBallPotted=false;railAfterContact=false;railContactCount=0;if(foul){current=1-current;setMessage(illegalBreak?"ILLEGAL BREAK • BALL IN HAND":wrongFirst?"FOUL • WRONG FIRST CONTACT":scratch?"SCRATCH • BALL IN HAND":"FOUL • NO RAIL OR POT");updateHud();return beginBallInHand()}if(!ownPotted)current=1-current;setMessage(ownPotted?"LEGAL POT • SHOOT AGAIN":"LEGAL SHOT • TURN PASSES");updateHud();if(!humanTurn())schedule(aiShoot,750)};
  const pocketBall=(ball,pocketIndex)=>{ball.active=false;ball.vx=ball.vy=0;shotPotted.push(ball.id);if(ball.id===0)scratch=true;else{objectBallPotted=true;if(ball.id===8)eightPocket=pocketIndex}sfx(ball.id===0?"lose":"coin")};
  const atPocketMouth=ball=>pockets.some(p=>Math.hypot(ball.x-p.x,ball.y-p.y)<34);
  const physics=dt=>{
    const step=dt/16.667;
    for(const ball of balls){
      if(!ball.active)continue;
      const speed=Math.hypot(ball.vx,ball.vy);ball.x+=ball.vx*step;ball.y+=ball.vy*step;ball.rotation+=(speed/R+ball.spinX)*step;ball.vx*=Math.pow(.9865,step);ball.vy*=Math.pow(.9865,step);ball.spinX*=Math.pow(.974,step);
      if(Math.hypot(ball.vx,ball.vy)<.045)ball.vx=ball.vy=0;
      let closestPocket=null,closestDistance=Infinity;
      for(const pocket of pockets){const distance=Math.hypot(ball.x-pocket.x,ball.y-pocket.y);if(distance<closestDistance){closestDistance=distance;closestPocket=pocket}}
      if(closestDistance<23.5){pocketBall(ball,pockets.indexOf(closestPocket));continue}
      const mouth=atPocketMouth(ball);
      if(mouth&&closestPocket){const dx=closestPocket.x-ball.x,dy=closestPocket.y-ball.y,distance=Math.max(1,closestDistance),funnel=(34-distance)*.0028;ball.vx+=dx/distance*funnel*step;ball.vy+=dy/distance*funnel*step;ball.vx*=.997;ball.vy*=.997}
      if(!mouth&&ball.x-R<rail.l){ball.x=rail.l+R;ball.vx=Math.abs(ball.vx)*.86;ball.vy=ball.vy*.965+ball.spinX*.35;ball.spinX*=.65;if(firstHit!==null){railAfterContact=true;railContactCount++}}
      if(!mouth&&ball.x+R>rail.r){ball.x=rail.r-R;ball.vx=-Math.abs(ball.vx)*.86;ball.vy=ball.vy*.965-ball.spinX*.35;ball.spinX*=.65;if(firstHit!==null){railAfterContact=true;railContactCount++}}
      if(!mouth&&ball.y-R<rail.t){ball.y=rail.t+R;ball.vy=Math.abs(ball.vy)*.86;ball.vx=ball.vx*.965-ball.spinX*.35;ball.spinX*=.65;if(firstHit!==null){railAfterContact=true;railContactCount++}}
      if(!mouth&&ball.y+R>rail.b){ball.y=rail.b-R;ball.vy=-Math.abs(ball.vy)*.86;ball.vx=ball.vx*.965+ball.spinX*.35;ball.spinX*=.65;if(firstHit!==null){railAfterContact=true;railContactCount++}}
    }
    for(let iteration=0;iteration<3;iteration++)for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){
      const a=balls[i],b=balls[j];if(!a.active||!b.active)continue;
      const dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy);if(!dist||dist>=R*2)continue;
      const nx=dx/dist,ny=dy/dist,overlap=R*2-dist,correction=Math.max(0,overlap-.01)*.52;a.x-=nx*correction;a.y-=ny*correction;b.x+=nx*correction;b.y+=ny*correction;
      const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;
      if(rel<0){const impulse=rel*.972,tx=-ny,ty=nx,tangent=(b.vx-a.vx)*tx+(b.vy-a.vy)*ty,friction=tangent*.018;a.vx+=(impulse*nx+friction*tx);a.vy+=(impulse*ny+friction*ty);b.vx-=(impulse*nx+friction*tx);b.vy-=(impulse*ny+friction*ty);a.spinX-=tangent*.01;b.spinX+=tangent*.01;if((a.id===0||b.id===0)&&firstHit===null){firstHit=a.id===0?b.id:a.id;if(!spinApplied){const cueBall=a.id===0?a:b;cueBall.vx+=shotDirectionX*shotSpinY*4.2;cueBall.vy+=shotDirectionY*shotSpinY*4.2;cueBall.spinX+=shotSpinX*1.4;spinApplied=true}}}
    }
  };
  const drawBall=ball=>{ctx.save();ctx.translate(ball.x,ball.y);ctx.rotate(ball.rotation);ctx.shadowColor=colors[ball.id];ctx.shadowBlur=10;ctx.fillStyle=colors[ball.id];ctx.beginPath();ctx.arc(0,0,R,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(ball.id>=9){ctx.fillStyle="#f5f0e6";ctx.beginPath();ctx.arc(0,0,R,0,Math.PI*2);ctx.fill();ctx.fillStyle=colors[ball.id];ctx.fillRect(-R,-5,R*2,10)}if(ball.id){ctx.fillStyle="#f8f5eb";ctx.beginPath();ctx.arc(0,0,6.5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.font="bold 7px monospace";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(ball.id,0,.5)}else{ctx.fillStyle="#dfefff";ctx.beginPath();ctx.arc(-4,-4,3,0,Math.PI*2);ctx.fill()}ctx.restore()};
  const predictedContact=()=>{const c=cue(),dx=Math.cos(aimAngle),dy=Math.sin(aimAngle);let best=null;for(const ball of balls){if(!ball.active||ball.id===0)continue;const ox=ball.x-c.x,oy=ball.y-c.y,projection=ox*dx+oy*dy;if(projection<=0)continue;const perpendicular2=ox*ox+oy*oy-projection*projection,diameter=R*2;if(perpendicular2>diameter*diameter)continue;const distance=projection-Math.sqrt(diameter*diameter-perpendicular2);if(distance>0&&(!best||distance<best.distance))best={ball,distance,x:c.x+dx*distance,y:c.y+dy*distance}}return best};
  const predictedRail=()=>{const c=cue(),dx=Math.cos(aimAngle),dy=Math.sin(aimAngle),left=rail.l+R,right=rail.r-R,top=rail.t+R,bottom=rail.b-R,candidates=[];if(dx>0)candidates.push({distance:(right-c.x)/dx,axis:"x"});else if(dx<0)candidates.push({distance:(left-c.x)/dx,axis:"x"});if(dy>0)candidates.push({distance:(bottom-c.y)/dy,axis:"y"});else if(dy<0)candidates.push({distance:(top-c.y)/dy,axis:"y"});const hit=candidates.filter(item=>item.distance>0).sort((a,b)=>a.distance-b.distance)[0];return hit?{...hit,x:c.x+dx*hit.distance,y:c.y+dy*hit.distance,reflected:hit.axis==="x"?Math.atan2(dy,-dx):Math.atan2(-dy,dx)}:null};
  const drawArena=()=>{
    ctx.fillStyle=arena.frame;ctx.fillRect(0,0,W,H);
    if(theme==="sunset"){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,"#ff8b62");sky.addColorStop(.42,"#5a1d56");sky.addColorStop(1,"#160d2c");ctx.fillStyle=sky;ctx.fillRect(8,8,W-16,H-16);ctx.fillStyle="#25112c";for(let x=12;x<W;x+=46){const h=16+(x*7%25);ctx.fillRect(x,H-18-h,34,h)}}
    else if(theme==="cosmic"){ctx.fillStyle="#09051d";ctx.fillRect(8,8,W-16,H-16);for(let i=0;i<90;i++){ctx.fillStyle=i%7?"#ffffff88":arena.glow;ctx.fillRect((i*83+17)%W,(i*47+11)%H,i%9?1:2,i%9?1:2)}}
    else if(theme==="arctic"){const ice=ctx.createLinearGradient(0,0,W,H);ice.addColorStop(0,"#d9fbff");ice.addColorStop(1,"#3c91b6");ctx.fillStyle=ice;ctx.fillRect(8,8,W-16,H-16);ctx.strokeStyle="#ffffff66";for(let x=20;x<W;x+=72){ctx.beginPath();ctx.moveTo(x,8);ctx.lineTo(x+38,43);ctx.lineTo(x+68,8);ctx.stroke()}}
    else{ctx.fillStyle="#17102d";ctx.fillRect(8,8,W-16,H-16);ctx.strokeStyle="#31f5ff33";for(let x=20;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,8);ctx.lineTo(x,42);ctx.stroke()}}
    ctx.fillStyle=arena.rail;ctx.fillRect(18,18,W-36,H-36);const felt=ctx.createRadialGradient(W*.5,H*.48,20,W*.5,H*.5,W*.58);felt.addColorStop(0,arena.felt2);felt.addColorStop(1,arena.felt);ctx.fillStyle=felt;ctx.fillRect(rail.l,rail.t,rail.r-rail.l,rail.b-rail.t);
    ctx.save();ctx.beginPath();ctx.rect(rail.l,rail.t,rail.r-rail.l,rail.b-rail.t);ctx.clip();ctx.globalAlpha=.16;ctx.strokeStyle=arena.accent;ctx.lineWidth=1;if(theme==="cosmic"){for(let i=0;i<55;i++){ctx.fillStyle=i%5?"#fff":arena.glow;ctx.fillRect(rail.l+(i*73)%810,rail.t+(i*41)%410,i%6?1:2,i%6?1:2)}}else if(theme==="arctic"){for(let x=70;x<880;x+=70){ctx.beginPath();ctx.moveTo(x,rail.t);ctx.lineTo(x+35,rail.b);ctx.stroke()}}else{for(let x=80;x<880;x+=80){ctx.beginPath();ctx.moveTo(x,rail.t);ctx.lineTo(x,rail.b);ctx.stroke()}for(let y=90;y<460;y+=80){ctx.beginPath();ctx.moveTo(rail.l,y);ctx.lineTo(rail.r,y);ctx.stroke()}}ctx.restore();
    ctx.strokeStyle=arena.accent;ctx.shadowColor=arena.glow;ctx.shadowBlur=9;ctx.lineWidth=3;ctx.strokeRect(rail.l+8,rail.t+8,rail.r-rail.l-16,rail.b-rail.t-16);ctx.shadowBlur=0;
    pockets.forEach((p,index)=>{ctx.fillStyle="#02030a";ctx.shadowColor=index===calledPocket?"#ffe84c":arena.glow;ctx.shadowBlur=index===calledPocket?24:12;ctx.beginPath();ctx.arc(p.x,p.y,23,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(index===calledPocket){ctx.strokeStyle="#ffe84c";ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,29,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#ffe84c";ctx.font="bold 11px monospace";ctx.textAlign="center";ctx.fillText("CALL",p.x,p.y+(p.y<H/2?43:-35))}});
  };
  const drawGuide=()=>{const c=cue(),dx=Math.cos(aimAngle),dy=Math.sin(aimAngle),contact=predictedContact(),railHit=predictedRail(),guideMode=!isAi||aiLevel==="easy"?"full":aiLevel==="normal"?"contact":"short",fullDistance=contact?contact.distance:railHit?.distance||320,distance=guideMode==="short"?Math.min(125,fullDistance):fullDistance,endX=c.x+dx*distance,endY=c.y+dy*distance;ctx.save();ctx.lineCap="round";ctx.setLineDash(aimLocked?[4,4]:[10,8]);ctx.strokeStyle=aimLocked?arena.accent:"#ffffffc8";ctx.lineWidth=1.7+power/100;ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(endX,endY);ctx.stroke();ctx.setLineDash([]);if(contact&&guideMode==="full"){const nx=(contact.ball.x-contact.x)/(R*2),ny=(contact.ball.y-contact.y)/(R*2),normalPower=Math.max(0,dx*nx+dy*ny),cueOutX=dx-nx*normalPower,cueOutY=dy-ny*normalPower,cueOutLength=Math.hypot(cueOutX,cueOutY);ctx.strokeStyle=arena.accent;ctx.globalAlpha=.9;ctx.lineWidth=2;ctx.beginPath();ctx.arc(contact.x,contact.y,R,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(contact.ball.x-nx*R,contact.ball.y-ny*R,3.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(contact.ball.x,contact.ball.y);ctx.lineTo(contact.ball.x+nx*(65+normalPower*65),contact.ball.y+ny*(65+normalPower*65));ctx.stroke();if(cueOutLength>.025){ctx.strokeStyle="#ffffff99";ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(contact.x,contact.y);ctx.lineTo(contact.x+cueOutX/cueOutLength*(45+cueOutLength*65),contact.y+cueOutY/cueOutLength*(45+cueOutLength*65));ctx.stroke();ctx.setLineDash([])}}else if(contact&&guideMode==="contact"){ctx.fillStyle=arena.accent;ctx.beginPath();ctx.arc(contact.x,contact.y,4,0,Math.PI*2);ctx.fill()}else if(!contact&&railHit&&guideMode==="full"){ctx.strokeStyle=arena.accent;ctx.globalAlpha=.72;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(railHit.x,railHit.y);ctx.lineTo(railHit.x+Math.cos(railHit.reflected)*95,railHit.y+Math.sin(railHit.reflected)*95);ctx.stroke();ctx.setLineDash([])}const pull=35+power*.45+(dragging?dragDistance*.38:0);ctx.globalAlpha=1;ctx.strokeStyle=arena.cue;ctx.shadowColor=arena.glow;ctx.shadowBlur=dragging?12:3;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(c.x-dx*pull,c.y-dy*pull);ctx.lineTo(c.x-dx*(pull+112),c.y-dy*(pull+112));ctx.stroke();ctx.restore()};
  const drawPlacement=()=>{ctx.save();ctx.globalAlpha=.82;ctx.fillStyle=placementValid?"#dffcff":"#ff335f";ctx.shadowColor=placementValid?arena.glow:"#ff335f";ctx.shadowBlur=18;ctx.beginPath();ctx.arc(placement.x,placement.y,R,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=placementValid?"#72ff77":"#ff335f";ctx.lineWidth=3;ctx.beginPath();ctx.arc(placement.x,placement.y,R+6,0,Math.PI*2);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font="bold 10px monospace";ctx.textAlign="center";ctx.fillText(placementValid?"CLICK / SPACE":"INVALID",placement.x,placement.y-24);ctx.restore()};
  const draw=()=>{ctx.clearRect(0,0,W,H);drawArena();if(!shotActive&&!ballInHand&&humanTurn()&&cue().active&&!ended)drawGuide();balls.filter(ball=>ball.active).forEach(drawBall);if(ballInHand&&humanTurn())drawPlacement()};
  const shoot=(angle=aimAngle,shotPower=power,aiCalledPocket=null)=>{if(ended||shotActive||ballInHand||anyMoving()||!cue().active)return;if(legalFirstTarget()==="eight"&&calledPocket===null&&aiCalledPocket===null){setMessage("CALL A POCKET BEFORE SHOOTING THE 8-BALL");updateHud();return}dragging=false;dragDistance=0;setAimLock(false);shotActive=true;shotTarget=legalFirstTarget();breakShot=shots===0;shotCalledPocket=aiCalledPocket??calledPocket;shots++;turnsTaken[current]++;shotPotted=[];scratch=false;firstHit=null;railAfterContact=false;objectBallPotted=false;railContactCount=0;eightPocket=null;spinApplied=false;shotSpinX=spinX;shotSpinY=spinY;const spinMagnitude=Math.min(1,Math.hypot(spinX,spinY)),accuracyDrift=(Math.random()*2-1)*spinMagnitude*.0055;angle+=accuracyDrift;shotDirectionX=Math.cos(angle);shotDirectionY=Math.sin(angle);const speed=5.5+shotPower*.145;cue().vx=shotDirectionX*speed;cue().vy=shotDirectionY*speed;cue().spinX=shotSpinX*1.35;setMessage(`${playerName(current)} SHOT ${shots}${spinMagnitude>.15?` • SPIN ${Math.round(spinMagnitude*100)}%`:""}`);updateHud();sfx("move")};
  const distancePointToSegment=(px,py,x1,y1,x2,y2)=>{const dx=x2-x1,dy=y2-y1,length2=dx*dx+dy*dy;if(!length2)return Math.hypot(px-x1,py-y1);const t=Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/length2)),x=x1+t*dx,y=y1+t*dy;return Math.hypot(px-x,py-y)};
  const pathClear=(from,to,ignoredBalls=[])=>balls.every(ball=>!ball.active||ignoredBalls.includes(ball.id)||distancePointToSegment(ball.x,ball.y,from.x,from.y,to.x,to.y)>R*2.05);
  const pathClearance=(from,to,ignoredBalls=[])=>balls.reduce((minimum,ball)=>!ball.active||ignoredBalls.includes(ball.id)?minimum:Math.min(minimum,distancePointToSegment(ball.x,ball.y,from.x,from.y,to.x,to.y)-R*2),120);
  const legalAiTargets=targetType=>balls.filter(ball=>ball.active&&ball.id!==0&&(targetType==="open"?ball.id!==8:targetType==="eight"?ball.id===8:groupOf(ball.id)===targetType));
  const planAiShots=()=>{const targetType=groups[1]?(remaining(groups[1])?groups[1]:"eight"):"open",c=cue(),targets=legalAiTargets(targetType),plans=[];for(const target of targets)for(let pocketIndex=0;pocketIndex<pockets.length;pocketIndex++){const pocket=pockets[pocketIndex],potDistance=Math.hypot(pocket.x-target.x,pocket.y-target.y);if(potDistance<1)continue;const objectX=(pocket.x-target.x)/potDistance,objectY=(pocket.y-target.y)/potDistance,contact={x:target.x-objectX*(R*2+.45),y:target.y-objectY*(R*2+.45)};if(!validCuePlacement(contact.x,contact.y)||!pathClear(c,contact,[0,target.id])||!pathClear(target,pocket,[target.id]))continue;const cueDistance=Math.hypot(contact.x-c.x,contact.y-c.y),shotX=(contact.x-c.x)/cueDistance,shotY=(contact.y-c.y)/cueDistance,cutAngle=Math.acos(Math.max(-1,Math.min(1,shotX*objectX+shotY*objectY)));if(cutAngle>1.38)continue;const clearance=Math.min(pathClearance(c,contact,[0,target.id]),pathClearance(target,pocket,[target.id])),normal=Math.max(0,shotX*objectX+shotY*objectY),tangentX=shotX-objectX*normal,tangentY=shotY-objectY*normal,tangentLength=Math.hypot(tangentX,tangentY),expected={x:contact.x+(tangentLength?tangentX/tangentLength:shotX)*75,y:contact.y+(tangentLength?tangentY/tangentLength:shotY)*75},pocketDistance=Math.min(...pockets.map(item=>Math.hypot(item.x-expected.x,item.y-expected.y))),scratchRisk=Math.max(0,78-pocketDistance)*4,nextTargets=targets.filter(ball=>ball.id!==target.id),nextOptions=nextTargets.filter(ball=>pathClear(expected,ball,[0,target.id,ball.id])).length,positionBonus=(aiLevel==="hard"||aiLevel==="champion")?nextOptions*24:nextOptions*6,score=cueDistance*.52+potDistance*.78+cutAngle*190+scratchRisk-clearance*1.4-positionBonus;plans.push({target,pocket,pocketIndex,contact,cueDistance,potDistance,cutAngle,clearance,scratchRisk,nextOptions,expected,score})}return plans.sort((a,b)=>a.score-b.score)};
  const planSafety=()=>{const targetType=groups[1]?(remaining(groups[1])?groups[1]:"eight"):"open",c=cue(),targets=legalAiTargets(targetType),options=[];for(const target of targets){const dx=target.x-c.x,dy=target.y-c.y,distance=Math.hypot(dx,dy),contact={x:target.x-dx/distance*(R*2+.5),y:target.y-dy/distance*(R*2+.5)};if(pathClear(c,contact,[0,target.id]))options.push({target,contact,distance,score:pathClearance(c,contact,[0,target.id])-distance*.02})}return options.sort((a,b)=>b.score-a.score)[0]||null};
  const aiShoot=()=>{if(ended||current!==1||shotActive||ballInHand)return;const plans=planAiShots(),level=aiLevel;let plan=null,safety=false;if(plans.length){if(level==="easy")plan=plans[Math.floor(Math.random()*Math.min(4,plans.length))];else plan=plans[0];if(level==="champion"&&(plan.cutAngle>.88||plan.scratchRisk>110)){const safe=planSafety();if(safe){plan=safe;safety=true}}else if(level==="normal"&&Math.random()<.1&&plans.length>1)plan=plans.find(item=>item.scratchRisk<plans[0].scratchRisk)||plans[0]}else{plan=planSafety();safety=true}if(!plan)return beginBallInHand();const baseAngle=Math.atan2(plan.contact.y-cue().y,plan.contact.x-cue().x),error={easy:.07,normal:.022,hard:.007,champion:.003}[level]*(Math.random()*2-1),angle=baseAngle+error,aiPower=safety?Math.min(62,Math.max(32,34+plan.distance*.045)):Math.min(94,Math.max(34,32+plan.cueDistance*.055+plan.potDistance*.025));spinX=level==="champion"?(Math.random()-.5)*.25:0;spinY=(level==="hard"||level==="champion")?Math.max(-.35,Math.min(.35,(plan.nextOptions||0)>.5?.18:-.12)):0;drawSpinControl();calledPocket=plan.pocketIndex??null;updateHud();setMessage(`${opponentName()} • ${safety?"SAFETY PLAN":"LEGAL POT LINE"}${plan.nextOptions!=null?` • ${plan.nextOptions} NEXT OPTIONS`:""}`);schedule(()=>shoot(angle,aiPower,plan.pocketIndex??null),650)};
  const spinLabel=()=>{const vertical=spinY>.2?"TOP":spinY<-.2?"BACK":"",horizontal=spinX>.2?"RIGHT":spinX<-.2?"LEFT":"";return[vertical,horizontal].filter(Boolean).join(" + ")||"CENTER"};
  const drawSpinControl=()=>{spinCtx.clearRect(0,0,100,100);const gradient=spinCtx.createRadialGradient(40,35,4,50,50,42);gradient.addColorStop(0,"#fff");gradient.addColorStop(1,"#b9c5dd");spinCtx.fillStyle=gradient;spinCtx.beginPath();spinCtx.arc(50,50,39,0,Math.PI*2);spinCtx.fill();spinCtx.strokeStyle=arena.accent;spinCtx.lineWidth=2;spinCtx.stroke();spinCtx.strokeStyle="#26304b66";spinCtx.lineWidth=1;spinCtx.beginPath();spinCtx.moveTo(11,50);spinCtx.lineTo(89,50);spinCtx.moveTo(50,11);spinCtx.lineTo(50,89);spinCtx.stroke();spinCtx.fillStyle="#10152a";spinCtx.beginPath();spinCtx.arc(50+spinX*34,50-spinY*34,6,0,Math.PI*2);spinCtx.fill();spinCtx.strokeStyle=arena.glow;spinCtx.lineWidth=2;spinCtx.stroke();$("#pool-spin-label").textContent=spinLabel()};
  const setSpinFromEvent=event=>{if(ended||shotActive||ballInHand||!humanTurn())return;const rect=spinCanvas.getBoundingClientRect(),dx=(event.clientX-rect.left)*100/rect.width-50,dy=(event.clientY-rect.top)*100/rect.height-50,length=Math.hypot(dx,dy),scale=length>34?34/length:1;spinX=Math.max(-1,Math.min(1,dx*scale/34));spinY=Math.max(-1,Math.min(1,-dy*scale/34));drawSpinControl()};
  const spinDown=event=>{if(ended||shotActive||ballInHand||!humanTurn())return;event.preventDefault();spinDragging=true;spinCanvas.setPointerCapture?.(event.pointerId);setSpinFromEvent(event)};
  const spinMove=event=>{if(spinDragging)setSpinFromEvent(event)};
  const spinUp=event=>{spinDragging=false;spinCanvas.releasePointerCapture?.(event.pointerId)};
  const pointerPoint=event=>{const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*W/rect.width,y:(event.clientY-rect.top)*H/rect.height}};
  const selectCalledPocket=index=>{calledPocket=Number(index);setMessage(`8-BALL POCKET ${calledPocket+1} CALLED`);updateHud()};
  const pointerAim=event=>{if(!humanTurn()||shotActive||ended)return;const point=pointerPoint(event);if(ballInHand){placement=point;placementValid=validCuePlacement(point.x,point.y);setMessage(placementValid?"VALID POSITION • CLICK OR SPACE TO PLACE":"INVALID CUE-BALL POSITION");return}if(aimLocked||dragging)return;setAimAngle(Math.atan2(point.y-cue().y,point.x-cue().x))};
  const pointerDown=event=>{if(!humanTurn()||shotActive||ended||event.button===2)return;event.preventDefault();const point=pointerPoint(event);if(ballInHand){placement=point;placementValid=validCuePlacement(point.x,point.y);if(placementValid)confirmCuePlacement();else setMessage("INVALID POSITION • MOVE AWAY FROM BALLS AND RAILS");return}if(legalFirstTarget()==="eight"){const pocketIndex=pockets.findIndex(pocket=>Math.hypot(point.x-pocket.x,point.y-pocket.y)<38);if(pocketIndex>=0){selectCalledPocket(pocketIndex);return}}if(!aimLocked)setAimAngle(Math.atan2(point.y-cue().y,point.x-cue().x),true);dragging=true;dragStart={x:event.clientX,y:event.clientY};dragDistance=0;canvas.setPointerCapture?.(event.pointerId);setMessage("PULL STRAIGHT BACK • RELEASE TO SHOOT")};
  const pointerDrag=event=>{if(!dragging)return pointerAim(event);const dx=event.clientX-dragStart.x,dy=event.clientY-dragStart.y,pull=-(dx*Math.cos(aimAngle)+dy*Math.sin(aimAngle));dragDistance=Math.max(0,pull);if(dragDistance>2){power=Math.max(10,Math.min(100,Math.round(8+dragDistance*.9)));powerInput.value=power;$("#pool-power-value").textContent=power+"%"}};
  const pointerUp=event=>{if(!dragging)return;dragging=false;canvas.releasePointerCapture?.(event.pointerId);if(dragDistance>=7){const lockedAngle=aimAngle,releasePower=power;dragDistance=0;shoot(lockedAngle,releasePower)}else{dragDistance=0;setAimLock(true);setMessage("AIM LOCKED • FINE-TUNE WITH A/D OR ARROWS");updateHud()}};
  const unlockAim=event=>{event?.preventDefault?.();if(!shotActive&&humanTurn()){dragging=false;dragDistance=0;setAimLock(false);setMessage("AIM FREE • MOVE THE POINTER TO ADJUST");updateHud()}};
  const keyHandler=event=>{if(activeGame!=="billiards"||launchScreenOpen)return;if(event.key==="Escape"&&aimLocked&&!gamePauseOpen){event.preventDefault();event.stopImmediatePropagation();unlockAim();return}if(!event.target?.matches?.("input")&&["ArrowLeft","ArrowRight","KeyA","KeyD"].includes(event.code)&&!ballInHand){event.preventDefault();nudgeAim(["ArrowLeft","KeyA"].includes(event.code)?-1:1,event.shiftKey?1:.25);return}if(event.code==="Space"){event.preventDefault();if(ballInHand)confirmCuePlacement();else if(humanTurn())shoot()}};
  canvas.addEventListener("pointermove",pointerDrag);canvas.addEventListener("pointerdown",pointerDown);canvas.addEventListener("pointerup",pointerUp);canvas.addEventListener("pointercancel",unlockAim);canvas.addEventListener("contextmenu",unlockAim);spinCanvas.addEventListener("pointerdown",spinDown);spinCanvas.addEventListener("pointermove",spinMove);spinCanvas.addEventListener("pointerup",spinUp);spinCanvas.addEventListener("pointercancel",spinUp);powerInput.oninput=()=>{power=Number(powerInput.value);$("#pool-power-value").textContent=power+"%"};nudgeButtons.forEach(button=>button.onclick=()=>nudgeAim(Number(button.dataset.poolNudge)));pocketButtons.forEach(button=>button.onclick=()=>selectCalledPocket(button.dataset.poolPocket));shootButton.onclick=()=>shoot();window.addEventListener("keydown",keyHandler,true);
  const FIXED_STEP=1000/180;
  const loop=now=>{if(ended)return;const dt=Math.min(50,now-last);last=now;if(!gamePauseOpen){if(!aimLocked&&!dragging&&!shotActive){aimAngle=normalizeAngle(aimAngle+angleDelta(aimAngle,aimTargetAngle)*Math.min(1,dt*.022));updateAngleReadout()}const movingBefore=anyMoving();if(movingBefore){accumulator=Math.min(accumulator+dt,FIXED_STEP*10);while(accumulator>=FIXED_STEP){physics(FIXED_STEP);accumulator-=FIXED_STEP}}else accumulator=0;if(shotActive&&movingBefore&&!anyMoving())resolveShot();draw()}raf=requestAnimationFrame(loop)};
  updateHud();drawSpinControl();draw();raf=requestAnimationFrame(loop);setActiveCleanup(()=>{ended=true;cancelAnimationFrame(raf);timeouts.forEach(clearTimeout);window.removeEventListener("keydown",keyHandler,true);canvas.removeEventListener("pointermove",pointerDrag);canvas.removeEventListener("pointerdown",pointerDown);canvas.removeEventListener("pointerup",pointerUp);canvas.removeEventListener("pointercancel",unlockAim);canvas.removeEventListener("contextmenu",unlockAim);spinCanvas.removeEventListener("pointerdown",spinDown);spinCanvas.removeEventListener("pointermove",spinMove);spinCanvas.removeEventListener("pointerup",spinUp);spinCanvas.removeEventListener("pointercancel",spinUp)});
}

GubuntuGames.register("billiards",startBilliards);
