"use strict";

function startQuiz(launchOptions={}){
  const stats=currentPlayer.gameStats.quiz||={plays:0,wins:0,losses:0,draws:0,best:null},careerAccuracy=stats.totalAnswers?Math.round((stats.totalCorrect||0)/stats.totalAnswers*100):0;
  setStage(`<div class="quiz-config"><div class="big-icon">🧠</div><h3>NEON QUIZ ARENA</h3><div class="quiz-config-grid"><label>CATEGORY<select id="quiz-category">${Object.entries(quizCategoryLabels).map(([value,label])=>`<option value="${value}">${label}</option>`).join("")}</select></label><label class="quiz-timed"><input id="quiz-timed" type="checkbox" checked> TIMED • 15 SECONDS</label></div><div><p class="eyebrow">RUN LENGTH</p><div class="quiz-lengths">${[5,10,20].map((n,i)=>`<button class="pixel-btn ${i===1?"primary":"secondary"}" data-quiz-length="${n}">${n} QUESTIONS</button>`).join("")}</div></div><button id="quiz-daily" class="pixel-btn daily-quiz">DAILY CHALLENGE • SAME 10 QUESTIONS FOR EVERY PROFILE</button><div class="quiz-career-strip"><span>ACCURACY <b>${careerAccuracy}%</b></span><span>LONGEST STREAK <b>${stats.longestCorrectStreak||0}</b></span><span>PERFECT RUNS <b>${stats.perfectRuns||0}</b></span><span>FASTEST <b>${Number.isFinite(stats.fastestAnswer)?`${stats.fastestAnswer.toFixed(2)}s`:"—"}</b></span></div><p id="quiz-config-note" class="result">Difficulty rises from easy to hard during every run.</p></div>`);
  const progressiveRun=(pool,length,random=Math.random)=>{const order={easy:0,medium:1,hard:2},groups=["easy","medium","hard"].map(level=>shuffle(pool.filter(q=>q.difficulty===level),random)),result=[];for(let i=0;i<length;i++){const desired=Math.min(2,Math.floor(i/Math.max(1,length/3))),group=groups[desired].length?groups[desired]:groups.find(items=>items.length);if(!group?.length)break;result.push(group.splice(Math.floor(random()*group.length),1)[0])}return result.sort((a,b)=>order[a.difficulty]-order[b.difficulty])};
  const seededRandom=seed=>{let value=[...seed].reduce((n,ch)=>(n*31+ch.charCodeAt(0))>>>0,2166136261);return()=>{value=(value*1664525+1013904223)>>>0;return value/4294967296}};
  $$('[data-quiz-length]').forEach(btn=>btn.onclick=()=>{const category=$("#quiz-category").value,timed=$("#quiz-timed").checked,length=Number(btn.dataset.quizLength),pool=quizQuestions.filter(q=>category==="mixed"||q.category===category),questions=progressiveRun(pool,length);if(questions.length<length)$("#quiz-config-note").textContent=`Only ${questions.length} unique questions are available for this category.`;if(!questions.length)return toast("NO QUESTIONS FOR THIS CATEGORY");runQuiz(questions,{timed,category,daily:false})});
  $("#quiz-daily").onclick=()=>{const random=seededRandom(`gubuntu-daily-${todayKey()}`),questions=progressiveRun([...quizQuestions],10,random);runQuiz(questions,{timed:true,category:"mixed",daily:true})};
}
function runQuiz(questions,options={}){
  let runQuestions=[...questions],index=0,correct=0,points=0,streak=0,longestStreak=0,timer=null,transitionTimer=null,remaining=15,locked=false,freezeUntil=0,answerStarted=0;
  const lifelines={remove:true,freeze:true,replace:true},reviews=[];
  const stopTimer=()=>{clearInterval(timer);timer=null},stopTransition=()=>{clearTimeout(transitionTimer);transitionTimer=null},stopQuiz=()=>{stopTimer();stopTransition()};
  const multiplier=()=>streak>=7?2:streak>=5?1.5:streak>=3?1.25:1;
  const finish=()=>{stopQuiz();const total=runQuestions.length,accuracy=Math.round(correct/Math.max(1,total)*100),stats=currentPlayer.gameStats.quiz||={plays:0,wins:0,losses:0,draws:0,best:null};stats.totalCorrect=(stats.totalCorrect||0)+correct;stats.totalAnswers=(stats.totalAnswers||0)+total;stats.longestCorrectStreak=Math.max(stats.longestCorrectStreak||0,longestStreak);if(accuracy===100)stats.perfectRuns=(stats.perfectRuns||0)+1;stats.categoryStats||={};const category=options.category||"mixed",categoryStat=stats.categoryStats[category]||={correct:0,total:0};categoryStat.correct+=correct;categoryStat.total+=total;stats.categoryStats[category]=categoryStat;stats.bestCategory=Object.entries(stats.categoryStats).sort((a,b)=>(b[1].correct/b[1].total)-(a[1].correct/a[1].total))[0]?.[0]||category;stats.lastRun={accuracy,points,category,daily:!!options.daily,at:new Date().toISOString()};const wrong=reviews.filter(item=>!item.good);setStage(`<div class="quiz-summary"><div class="big-icon">${accuracy===100?"🏆":"🧠"}</div><h3>${options.daily?"DAILY CHALLENGE":"QUIZ COMPLETE"} • ${correct}/${total}</h3><div class="career-grid"><article><span>🎯</span><b>${accuracy}%</b><small>Accuracy</small></article><article><span>⚡</span><b>${points}</b><small>Score</small></article><article><span>🔥</span><b>${longestStreak}</b><small>Best streak</small></article><article><span>👑</span><b>${quizCategoryLabels[stats.bestCategory]||stats.bestCategory}</b><small>Best category</small></article><article><span>⏱</span><b>${Number.isFinite(stats.fastestAnswer)?`${stats.fastestAnswer.toFixed(2)}s`:"—"}</b><small>Fastest answer</small></article><article><span>💯</span><b>${stats.perfectRuns||0}</b><small>Perfect runs</small></article></div>${wrong.length?`<section class="quiz-review"><h4>INCORRECT ANSWERS</h4>${wrong.map(item=>`<article><b>${esc(item.question)}</b><span>Your answer: ${esc(item.answer)}</span><strong>Correct: ${esc(item.correctAnswer)}</strong></article>`).join("")}</section>`:`<p class="perfect-run">PERFECT RUN • NO INCORRECT ANSWERS</p>`}<button id="quiz-again" class="pixel-btn primary">NEW QUIZ RUN</button></div>`);reward(Math.round(points/120),Math.max(5,Math.round(points/80)),{result:accuracy>=60?"win":"loss",score:points});$("#quiz-again").onclick=startQuiz};
  const show=()=>{stopTimer();locked=false;if(index===runQuestions.length){finish();return}const q=runQuestions[index];remaining=15;freezeUntil=0;answerStarted=performance.now();setStage(`<div class="game-score quiz-scorebar">QUESTION ${index+1}/${runQuestions.length} • SCORE ${points} • STREAK ${streak} • MULTIPLIER x${multiplier()} • ${q.difficulty.toUpperCase()}</div>${options.timed?`<div class="quiz-timer"><i id="quiz-time-fill"></i></div>`:""}<div class="quiz-lifelines"><button data-life="remove" ${lifelines.remove?"":"disabled"}>−1 WRONG</button><button data-life="freeze" ${lifelines.freeze?"":"disabled"}>FREEZE 5s</button><button data-life="replace" ${lifelines.replace?"":"disabled"}>REPLACE</button></div><h3>${esc(q.question)}</h3><div>${q.answers.map((answer,i)=>`<button class="choice-btn quiz-answer" data-i="${i}">${String.fromCharCode(65+i)} • ${esc(answer)}</button>`).join("")}</div><p id="quiz-result" class="result quiz-feedback"></p>`);
    const answer=choice=>{if(locked)return;locked=true;stopTimer();const elapsed=(performance.now()-answerStarted)/1000,good=choice===q.correct,chosen=choice<0?"TIME EXPIRED":q.answers[choice];if(good){correct++;streak++;longestStreak=Math.max(longestStreak,streak);points+=Math.round(100*multiplier());statsFast(elapsed)}else streak=0;reviews.push({question:q.question,answer:chosen,correctAnswer:q.answers[q.correct],good});const result=$("#quiz-result");result.classList.add(good?"correct":"wrong");result.textContent=good?`CORRECT • x${multiplier()} STREAK BONUS`:`${chosen} • CORRECT: ${q.answers[q.correct]}`;$$('.quiz-answer').forEach((button,i)=>{button.disabled=true;if(i===q.correct)button.classList.add("correct")});stopTransition();transitionTimer=setTimeout(()=>{transitionTimer=null;index++;show()},good?850:1500)};
    const statsFast=elapsed=>{const stats=currentPlayer.gameStats.quiz||={};stats.fastestAnswer=Math.min(Number.isFinite(stats.fastestAnswer)?stats.fastestAnswer:Infinity,elapsed)};
    $$(".quiz-answer").forEach(btn=>btn.onclick=()=>answer(Number(btn.dataset.i)));
    $$('[data-life]').forEach(button=>button.onclick=()=>{const life=button.dataset.life;if(!lifelines[life]||locked)return;lifelines[life]=false;if(life==="remove"){const wrong=$$(".quiz-answer").find(btn=>Number(btn.dataset.i)!==q.correct&&!btn.disabled);if(wrong){wrong.disabled=true;wrong.classList.add("lifeline-removed")}button.disabled=true}else if(life==="freeze"){freezeUntil=Date.now()+5000;button.disabled=true;$("#quiz-result").textContent="TIMER FROZEN FOR 5 SECONDS"}else{const used=new Set(runQuestions.map(item=>item.key)),pool=quizQuestions.filter(item=>!used.has(item.key)&&(options.category==="mixed"||item.category===options.category));if(pool.length)runQuestions[index]=pool[Math.floor(Math.random()*pool.length)];show()}});
    if(options.timed)timer=setInterval(()=>{if(Date.now()<freezeUntil)return;remaining=Math.max(0,remaining-.2);$("#quiz-time-fill")?.style.setProperty("width",`${remaining/15*100}%`);if(remaining<=0)answer(-1)},200);
  };
  setActiveCleanup(stopQuiz);show();
}

GubuntuGames.register("quiz",startQuiz);
