"use strict";

function startSlots(){
  const stats=currentPlayer.gameStats.slots||={plays:0,wins:0,losses:0,draws:0,best:null},symbols=["🍒","🍋","🔔","⭐","7️⃣"],payouts={"🍒":4,"🍋":5,"🔔":8,"⭐":12,"7️⃣":25},sessionStartBalance=currentPlayer.coins;
  const timers=new Set(),schedule=(fn,delay)=>{const id=setTimeout(()=>{timers.delete(id);fn()},delay);timers.add(id)};let bet=Math.min(10,Math.max(1,currentPlayer.coins)),bonusMeter=0,inBonus=false,freeSpins=0,bonusPending=false,locked=false,losingStreak=0,spinTimer=null;
  const stopSpin=()=>{clearInterval(spinTimer);spinTimer=null},stop=()=>{stopSpin();timers.forEach(clearTimeout);timers.clear()};
  const updateSessionRecords=payout=>{stats.largestSinglePayout=Math.max(stats.largestSinglePayout||0,payout);stats.longestLosingStreak=Math.max(stats.longestLosingStreak||0,losingStreak);stats.highestBalanceGained=Math.max(stats.highestBalanceGained||0,currentPlayer.coins+payout-sessionStartBalance)};
  const render=()=>{const table=symbols.map(symbol=>`<span>${symbol}<b>×${payouts[symbol]}</b></span>`).join("");setStage(`<div class="slots42"><div class="game-score">${inBonus?`BONUS MODE • ${freeSpins} FREE SPINS LEFT • WINNINGS ×2`:`SESSION GAIN ${Math.max(0,currentPlayer.coins-sessionStartBalance)} • BEST PAYOUT ${stats.largestSinglePayout||0}`}</div><h3>NEON SLOTS PROGRESSION</h3>${inBonus?"":wagerHtml("slot42",bet)}<div class="slots-payouts">${table}</div><div class="slots bonus-reels" id="reels42">🍒 │ 🍋 │ ⭐</div><div class="slots-meter"><header><span>BONUS METER</span><b>${Math.round(bonusMeter)}%</b></header><i><em style="width:${bonusMeter}%"></em></i><small>${inBonus?"5 FREE SPINS • ALL WINNINGS DOUBLED":"LOSS +10% • SMALL WIN +5%"}</small></div><div class="slots-records"><span>LARGEST PAYOUT <b>${stats.largestSinglePayout||0}</b></span><span>LONGEST LOSS STREAK <b>${stats.longestLosingStreak||0}</b></span><span>BONUS ROUNDS <b>${stats.bonusRoundsActivated||0}</b></span><span>BEST SESSION GAIN <b>${stats.highestBalanceGained||0}</b></span></div><button id="spin42" class="pixel-btn primary">${inBonus?`FREE SPIN ${6-freeSpins}/5`:`SPIN • ${bet} ●`}</button><p id="slots42-result" class="result">Match three symbols for the listed multiplier. Two symbols return ×1.5.</p></div>`);if(!inBonus)bindWager("slot42",value=>{bet=safeBet(value);render()});$("#spin42").onclick=()=>spin(inBonus)};
  const afterSettlement=()=>{locked=false;if(inBonus&&freeSpins<=0){inBonus=false;bonusMeter=0;$("#slots42-result").textContent="BONUS COMPLETE • METER RESET";return schedule(render,800)}if(bonusPending)return beginBonus();render()};
  const settle=(amount,label)=>{updateSessionRecords(amount);reward(amount,amount>bet?12:amount?7:3,{result:amount>bet?"win":amount?"draw":"loss",score:amount});const message=$("#slots42-result");if(message)message.textContent=label;schedule(afterSettlement,700)};
  const offerRisk=payout=>{locked=false;setStage(`<div class="slots-risk"><p class="eyebrow">PAYOUT SECURED • ${payout} COINS</p><h3>COLLECT OR DOUBLE?</h3><div class="risk-card"><span>${payout}</span><small>50% ×2 • 50% LOSE PAYOUT</small></div><div class="game-actions"><button id="slots-collect" class="pixel-btn secondary">COLLECT</button><button id="slots-double" class="pixel-btn primary">DOUBLE</button></div><p id="slots-risk-result" class="result">The original stake is already paid. Only this payout is at risk.</p></div>`);$("#slots-collect").onclick=()=>{if(locked)return;locked=true;settle(payout,`COLLECTED • +${payout}`)};$("#slots-double").onclick=()=>{if(locked)return;locked=true;const won=Math.random()<.5,amount=won?payout*2:0;$("#slots-risk-result").textContent=won?`DOUBLE SUCCESS • +${amount}`:"DOUBLE FAILED • PAYOUT LOST";schedule(()=>settle(amount,won?`DOUBLE SUCCESS • +${amount}`:"RISK LOST • +0"),650)}};
  const resolveSpin=result=>{const counts=new Map();result.forEach(symbol=>counts.set(symbol,(counts.get(symbol)||0)+1));const [matchSymbol,matchCount]=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0];let payout=matchCount===3?bet*payouts[matchSymbol]:matchCount===2?Math.round(bet*1.5):0;if(inBonus)payout*=2;if(inBonus)freeSpins--;if(!inBonus){if(payout===0)bonusMeter=Math.min(100,bonusMeter+10);else if(matchCount===2)bonusMeter=Math.min(100,bonusMeter+5);if(bonusMeter>=100)bonusPending=true}if(payout===0){losingStreak++;updateSessionRecords(0)}else losingStreak=0;$("#reels42").textContent=result.join(" │ ");const label=payout?`${matchCount===3?`${matchSymbol} JACKPOT`:`TWO ${matchSymbol}`} • ${inBonus?"BONUS ×2 • ":""}+${payout}`:`NO MATCH • BONUS ${Math.round(bonusMeter)}%`;if(payout>bet)return offerRisk(payout);settle(payout,label)};
  const spin=free=>{if(locked)return;if(!free&&currentPlayer.coins<bet)return toast("NOT ENOUGH COINS");locked=true;if(!free){currentPlayer.coins-=bet;saveData();updateHud()}const reels=$("#reels42"),button=$("#spin42");button.disabled=true;reels.classList.add("spin");let ticks=0;stopSpin();spinTimer=setInterval(()=>{reels.textContent=Array.from({length:3},()=>symbols[Math.floor(Math.random()*symbols.length)]).join(" │ ");if(++ticks>10){stopSpin();reels.classList.remove("spin");resolveSpin(Array.from({length:3},()=>symbols[Math.floor(Math.random()*symbols.length)]))}},65)};
  const beginBonus=()=>{bonusPending=false;inBonus=true;freeSpins=5;bonusMeter=100;stats.bonusRoundsActivated=(stats.bonusRoundsActivated||0)+1;saveData();setStage(`<div class="slots-bonus-intro"><p class="eyebrow">BONUS METER FULL</p><h3>BONUS MODE</h3><div class="big-icon">⚡🎰⚡</div><b>5 FREE SPINS</b><p>WINNINGS ARE DOUBLED</p><button id="bonus-start" class="pixel-btn primary">START BONUS</button></div>`);$("#bonus-start").onclick=render};
  setActiveCleanup(stop);render();
}

GubuntuGames.register("slots",startSlots);
