"use strict";

function startTtt(launchOptions=null,legacyDifficulty=null){
  const preselectedMode=typeof launchOptions==="string"?launchOptions:launchOptions?.mode,preselectedDifficulty=typeof launchOptions==="string"?legacyDifficulty:launchOptions?.difficulty;
  const stats=currentPlayer.gameStats.ttt||={plays:0,wins:0,losses:0,draws:0,best:null};stats.records||={};stats.unlockedSkins||=["neon"];
  const skinDefs={neon:{name:"NEON GRID",className:"skin-neon"},solar:{name:"SOLAR BOARD",className:"skin-solar"},void:{name:"VOID MATRIX",className:"skin-void"}};
  if(["classic","four","survival"].includes(preselectedMode))return beginTtt(preselectedMode,["easy","normal","hard"].includes(preselectedDifficulty)?preselectedDifficulty:"normal",stats.unlockedSkins[0]||"neon");
  setStage(`<div class="ttt-setup arcade-mode-select"><p class="eyebrow">TACTICAL GRID LEAGUE</p><h3>NEON TIC-TAC-TOE</h3><div class="arcade-mode-grid"><button data-ttt-mode="classic"><b>CLASSIC 3×3</b><small>Three in a row • Best of three</small></button><button data-ttt-mode="four"><b>FOUR-IN-A-ROW</b><small>5×5 board • Connect four</small></button><button data-ttt-mode="survival"><b>SURVIVAL</b><small>Defeat increasingly stronger CPUs without losing</small></button></div><div class="ttt-options"><label>CPU LEVEL<select id="ttt-difficulty"><option value="easy">EASY</option><option value="normal" selected>NORMAL</option><option value="hard">HARD</option></select></label><label>BOARD SKIN<select id="ttt-skin">${stats.unlockedSkins.map(id=>`<option value="${id}">${skinDefs[id]?.name||id}</option>`).join("")}</select></label></div><p class="result">Solar unlocks after 3 series wins • Void unlocks at Survival streak 3.</p></div>`);
  $$('[data-ttt-mode]').forEach(button=>button.onclick=()=>beginTtt(button.dataset.tttMode,$("#ttt-difficulty").value,$("#ttt-skin").value));
  function beginTtt(mode,chosenDifficulty,skin){
    let difficulty=mode==="survival"?"easy":chosenDifficulty,size=mode==="four"?5:3,needed=mode==="four"?4:3,board=[],round=1,playerSeries=0,cpuSeries=0,survivalStreak=0,over=false,ended=false,cpuTimer=null,playerTurn=true;
    const recordKey=mode==="survival"?"adaptive":difficulty;stats.records[mode]||={};const record=stats.records[mode][recordKey]||={wins:0,losses:0,draws:0,seriesWins:0,bestStreak:0};stats.records[mode][recordKey]=record;
    const allLines=(boardSize,winLength)=>{const lines=[];for(let y=0;y<boardSize;y++)for(let x=0;x<=boardSize-winLength;x++)lines.push(Array.from({length:winLength},(_,i)=>y*boardSize+x+i));for(let x=0;x<boardSize;x++)for(let y=0;y<=boardSize-winLength;y++)lines.push(Array.from({length:winLength},(_,i)=>(y+i)*boardSize+x));for(let y=0;y<=boardSize-winLength;y++)for(let x=0;x<=boardSize-winLength;x++)lines.push(Array.from({length:winLength},(_,i)=>(y+i)*boardSize+x+i));for(let y=0;y<=boardSize-winLength;y++)for(let x=winLength-1;x<boardSize;x++)lines.push(Array.from({length:winLength},(_,i)=>(y+i)*boardSize+x-i));return lines};
    let lines=allLines(size,needed);
    const winner=b=>{const line=lines.find(indices=>indices.every(index=>b[index]&&b[index]===b[indices[0]]));return line?{mark:b[line[0]],line}:null};
    const available=b=>b.map((value,index)=>value?null:index).filter(index=>index!==null);
    const minimax=(state,maximizing,depth=0)=>{const won=winner(state);if(won)return won.mark==="O"?10-depth:depth-10;if(state.every(Boolean))return 0;const scores=available(state).map(index=>{state[index]=maximizing?"O":"X";const score=minimax(state,!maximizing,depth+1);state[index]=null;return score});return maximizing?Math.max(...scores):Math.min(...scores)};
    const immediateMove=(mark,state=board)=>available(state).find(index=>{state[index]=mark;const won=winner(state)?.mark===mark;state[index]=null;return won});
    const lineScore=state=>lines.reduce((total,line)=>{const own=line.filter(index=>state[index]==="O").length,enemy=line.filter(index=>state[index]==="X").length;if(own&&enemy)return total;return total+own*own-enemy*enemy*1.2},0);
    const hardMove=()=>{const empty=available(board);if(size===3){let best=-Infinity,picks=[];empty.forEach(index=>{board[index]="O";const score=minimax(board,false);board[index]=null;if(score>best){best=score;picks=[index]}else if(score===best)picks.push(index)});return picks[Math.floor(Math.random()*picks.length)]}let best=-Infinity,picks=[];empty.forEach(index=>{board[index]="O";let score=winner(board)?.mark==="O"?10000:lineScore(board);board[index]=null;board[index]="X";if(winner(board)?.mark==="X")score+=8500;board[index]=null;if(score>best){best=score;picks=[index]}else if(score===best)picks.push(index)});return picks[Math.floor(Math.random()*picks.length)]};
    const cpuPick=()=>{const empty=available(board),win=immediateMove("O");if(difficulty==="easy")return Math.random()<.2&&win!=null?win:empty[Math.floor(Math.random()*empty.length)];const block=immediateMove("X");if(difficulty==="normal")return win??block??(board[Math.floor(board.length/2)]?null:Math.floor(board.length/2))??empty[Math.floor(Math.random()*empty.length)];return win??block??hardMove()};
    const drawBoard=()=>{$$(".ttt-cell").forEach((cell,index)=>{cell.textContent=board[index]||"";cell.disabled=!!board[index]||over||!playerTurn;cell.classList.toggle("mark-x",board[index]==="X");cell.classList.toggle("mark-o",board[index]==="O")})};
    const updateStatus=(text="")=>{const result=$("#ttt-result");if(result)result.textContent=text||`${playerTurn?"YOUR TURN":"CPU THINKING"} • ${difficulty.toUpperCase()}`;const score=$("#ttt-series");if(score)score.textContent=mode==="survival"?`SURVIVAL STREAK ${survivalStreak}`:`YOU ${playerSeries} — ${cpuSeries} CPU`};
    const unlockSkins=()=>{const seriesWins=Object.values(stats.records).flatMap(group=>Object.values(group)).reduce((sum,item)=>sum+(item.seriesWins||0),0);if(seriesWins>=3&&!stats.unlockedSkins.includes("solar"))stats.unlockedSkins.push("solar");if(record.bestStreak>=3&&!stats.unlockedSkins.includes("void"))stats.unlockedSkins.push("void")};
    const finishRun=won=>{if(ended)return;ended=true;clearTimeout(cpuTimer);record.bestStreak=Math.max(record.bestStreak||0,survivalStreak);if(won){record.seriesWins++;record.wins++}else record.losses++;unlockSkins();setStage(`<div class="ttt-report"><h3>${won?"GRID VICTORY 🏆":"CPU VICTORY"}</h3><div class="career-grid"><article><span>MODE</span><b>${mode.toUpperCase()}</b></article><article><span>CPU</span><b>${recordKey.toUpperCase()}</b></article><article><span>BEST STREAK</span><b>${record.bestStreak}</b></article><article><span>SERIES WINS</span><b>${record.seriesWins}</b></article></div><p>UNLOCKED SKINS: ${stats.unlockedSkins.map(id=>skinDefs[id]?.name||id).join(" • ")}</p><button id="ttt-again" class="pixel-btn primary">NEW MATCH</button></div>`);reward(won?40+survivalStreak*10:5,won?35:8,{result:won?"win":"loss",score:mode==="survival"?survivalStreak:playerSeries});$("#ttt-again").onclick=startTtt};
    const nextBoard=()=>{over=false;board=Array(size*size).fill(null);playerTurn=round%2===1;setStage(`<div class="game-score"><b id="ttt-series"></b> • ROUND ${round} • ${mode==="four"?"5×5 CONNECT 4":"3×3 CONNECT 3"}</div><div class="ttt-grid ttt-run-grid ${skinDefs[skin]?.className||"skin-neon"}" style="--ttt-size:${size}">${board.map((_,index)=>`<button class="ttt-cell" data-i="${index}"></button>`).join("")}</div><p id="ttt-result" class="result"></p>`);$$(".ttt-cell").forEach(cell=>cell.onclick=()=>playerMove(Number(cell.dataset.i)));updateStatus();drawBoard();if(!playerTurn)cpuTimer=setTimeout(cpuMove,450)};
    const resolveBoard=()=>{const won=winner(board);if(won){won.line.forEach(index=>$$('.ttt-cell')[index]?.classList.add("winning"));over=true;if(won.mark==="X"){if(mode==="survival"){survivalStreak++;record.wins++;record.bestStreak=Math.max(record.bestStreak,survivalStreak);round++;difficulty=survivalStreak>=2?"hard":survivalStreak>=1?"normal":"easy";updateStatus(`CPU DEFEATED • NEXT: ${difficulty.toUpperCase()}`);cpuTimer=setTimeout(nextBoard,900);return true}playerSeries++}else{if(mode==="survival"){updateStatus("SURVIVAL RUN LOST");cpuTimer=setTimeout(()=>finishRun(false),900);return true}cpuSeries++}updateStatus(won.mark==="X"?"ROUND WON":"ROUND LOST");if(playerSeries>=2||cpuSeries>=2){cpuTimer=setTimeout(()=>finishRun(playerSeries>=2),900);return true}round++;cpuTimer=setTimeout(nextBoard,900);return true}if(board.every(Boolean)){over=true;record.draws++;updateStatus("DRAW • STARTER ROTATES");round++;cpuTimer=setTimeout(nextBoard,800);return true}return false};
    const playerMove=index=>{if(ended||over||!playerTurn||board[index])return;board[index]="X";drawBoard();if(resolveBoard())return;playerTurn=false;updateStatus();drawBoard();cpuTimer=setTimeout(cpuMove,350)};
    const cpuMove=()=>{if(ended||over)return;const pick=cpuPick();if(pick==null)return;board[pick]="O";drawBoard();if(resolveBoard())return;playerTurn=true;updateStatus();drawBoard()};
    nextBoard();setActiveCleanup(()=>{ended=true;clearTimeout(cpuTimer)});
  }
}

GubuntuGames.register("ttt",startTtt);
